#!/usr/bin/env python3
"""ccwho engine - all the logic. HOT-RELOADED by the runner on every tick.

Keep this module free of long-lived objects: the runner calls importlib.reload()
each iteration so edits land in a running watch without restarting it. Only pure
functions and plain dicts cross the boundary; state lives in the runner and is
passed back in, the way network_check_ruby carries @options between ticks.

Reads only what Claude Code already writes to disk. No daemon, no hooks, no tmux.

  claude agents --json      -> name, cwd, status, waitingFor, pid, sessionId
  ~/.claude/projects/**/    -> <sessionId>.jsonl transcript, for the real topic
  ps                        -> processes reparented to PID 1, matched by sessionId
"""
from __future__ import annotations

import glob
import json
import os
import shutil
import subprocess
import sys
import time

# Status order: what needs you first, what is working next, what is parked last.
_RANK = {"waiting": 0, "busy": 1, "shell": 2, "idle": 3}
_UNKNOWN_RANK = 4


# ---------------------------------------------------------------- pure helpers

def parse_sessions(raw):
    """Parse `claude agents --json`. A broken feed is empty, never an exception."""
    try:
        data = json.loads(raw)
    except (ValueError, TypeError):
        return []
    return data if isinstance(data, list) else []


def project_of(cwd):
    """Repo name for a cwd. A worktree reports its parent repo, not the branch dir."""
    if not cwd:
        return "?"
    parts = [p for p in cwd.split("/") if p]
    if not parts:
        return "?"
    for marker in (".claude", ".git"):
        if marker in parts:
            i = parts.index(marker)
            if i > 0:
                return parts[i - 1]
    return parts[-1]


def _text_of(content):
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        return " ".join(
            b.get("text", "") for b in content if isinstance(b, dict) and b.get("type") == "text"
        )
    return ""


# Prompts the harness injects as "user" turns. They are never what the session is about.
_BOILERPLATE = (
    "Base directory for this skill:",
    "This session is being continued from a previous conversation",
    "Caveat: The messages below were generated by the user",
    "<",
)


def is_boilerplate(text):
    return text.startswith(_BOILERPLATE)


def extract_topic(lines, strict=False):
    """First and last real user prompt. Skips tool noise and system reminders."""
    real, any_prompt = [], []
    for line in lines:
        try:
            d = json.loads(line)
        except (ValueError, TypeError):
            continue
        if not isinstance(d, dict) or d.get("type") != "user":
            continue
        text = " ".join(_text_of(d.get("message", {}).get("content")).split())
        if not text:
            continue
        any_prompt.append(text)
        if not is_boilerplate(text):
            real.append(text)
    # Prefer a genuine prompt. In strict mode report nothing rather than harness noise,
    # so the caller can widen its search window instead of printing a task-notification.
    if strict:
        pool = real
    else:
        pool = real or [t for t in any_prompt if not t.startswith("<")] or any_prompt
    return {"first": pool[0] if pool else "", "last": pool[-1] if pool else ""}


def extract_title(lines):
    """Claude Code's own generated session title (`ai-title` entries)."""
    title = ""
    for line in lines:
        try:
            d = json.loads(line)
        except (ValueError, TypeError):
            continue
        if isinstance(d, dict) and d.get("type") == "ai-title" and d.get("aiTitle"):
            title = str(d["aiTitle"]).strip()
    return title


# Tools whose most useful hint is the file they touch.
_FILE_TOOLS = ("Edit", "Read", "Write", "NotebookEdit")


def _tool_hint(name, inp):
    if name == "Bash":
        return inp.get("description") or inp.get("command") or ""
    if name in _FILE_TOOLS:
        return os.path.basename(inp.get("file_path") or "")
    return inp.get("pattern") or inp.get("description") or inp.get("query") or ""


def extract_doing(lines):
    """What the session last actually did - the final tool call, human-readable."""
    doing = ""
    for line in lines:
        try:
            d = json.loads(line)
        except (ValueError, TypeError):
            continue
        if not isinstance(d, dict) or d.get("type") != "assistant":
            continue
        content = d.get("message", {}).get("content")
        if not isinstance(content, list):
            continue
        for b in content:
            if isinstance(b, dict) and b.get("type") == "tool_use":
                name = b.get("name", "?")
                hint = " ".join(str(_tool_hint(name, b.get("input", {}) or {})).split())
                doing = f"{name}: {hint}" if hint else name
    return doing


def since(mtime, now=None):
    """Time since last transcript write - real activity, unlike session start age."""
    if mtime is None or not isinstance(mtime, (int, float)):
        return "?"
    secs = max(0, int((time.time() if now is None else now) - mtime))
    if secs < 60:
        return f"{secs}s"
    if secs < 3600:
        return f"{secs // 60}m"
    if secs < 86400:
        return f"{secs // 3600}h"
    return f"{secs // 86400}d"


def attribute_orphans(ps_output, session_ids):
    """Map sessionId -> count of processes reparented to PID 1 whose cmdline names it.

    This is the detached-work blind spot: work a session launched with `&` or nohup
    outlives it, is adopted by PID 1, and the session then reports idle.
    """
    counts = {sid: 0 for sid in session_ids}
    for pid, ppid, cmd in _ps_rows(ps_output):
        if ppid != 1:
            continue
        for sid in session_ids:
            if sid and sid in cmd:
                counts[sid] += 1
    return counts


def count_orphans(ps_output, home=None):
    """Orphans reparented to PID 1. With `home`, count only work under it -
    macOS has hundreds of system daemons on PID 1 and none of them are yours."""
    total = 0
    for _pid, ppid, cmd in _ps_rows(ps_output):
        if ppid != 1:
            continue
        if home and home not in cmd:
            continue
        total += 1
    return total


def _ps_rows(ps_output):
    for line in (ps_output or "").splitlines():
        fields = line.strip().split(None, 2)
        if len(fields) < 3 or not fields[1].isdigit():
            continue
        yield fields[0], int(fields[1]), fields[2]


def gate_line(gate_dir=None):
    """One line naming who currently holds a ccgate slot, if anyone does."""
    try:
        import ccgate
    except ImportError:
        return ""
    gate_dir = gate_dir if gate_dir is not None else ccgate.GATE_DIR
    held = [h for h in ccgate.gate_status(gate_dir) if h.get("alive", True)]
    if not held:
        return ""
    who = ", ".join(f"{h.get('label') or '?'}({int(time.time() - h.get('since', time.time()))}s)"
                    for h in held)
    return f"{len(held)} gate slot(s) held: {who}"


def sort_key(row):
    return (_RANK.get(row.get("status"), _UNKNOWN_RANK), row.get("project", ""), row.get("name", ""))


def age(started_ms, now=None):
    # `not started_ms` would swallow epoch 0, which is a valid timestamp.
    if started_ms is None or not isinstance(started_ms, (int, float)):
        return "?"
    now = int(time.time() * 1000) if now is None else now
    mins = max(0, (now - started_ms) // 60000)
    if mins < 60:
        return f"{mins}m"
    if mins < 1440:
        return f"{mins // 60}h"
    return f"{mins // 1440}d"


def truncate(s, width):
    s = s or ""
    return s if len(s) <= width else s[: max(0, width - 1)] + "…"


# ------------------------------------------------------------------ disk reads

def transcript_path(session_id):
    if not session_id:
        return None
    hits = glob.glob(os.path.expanduser(f"~/.claude/projects/*/{session_id}.jsonl"))
    return hits[0] if hits else None


def read_windows(session_id, tail_bytes=4 * 1024 * 1024, head_lines=400):
    """Head and tail of a transcript, plus its mtime. One read, several extractors."""
    path = transcript_path(session_id)
    if not path:
        return [], [], None
    try:
        head = []
        with open(path, "r", errors="ignore") as fh:
            for _ in range(head_lines):
                line = fh.readline()
                if not line:
                    break
                head.append(line)
        with open(path, "rb") as fh:
            fh.seek(0, os.SEEK_END)
            fh.seek(max(0, fh.tell() - tail_bytes))
            tail = fh.read().decode("utf-8", "ignore").splitlines()[1:]
        return head, tail, os.path.getmtime(path)
    except OSError:
        return [], [], None


def topic_for(session_id, tail_bytes=4 * 1024 * 1024, head_lines=400):
    """Head+tail read only. Transcripts reach hundreds of MB; never read the whole file."""
    path = transcript_path(session_id)
    if not path:
        return {"first": "", "last": ""}
    try:
        head = []
        with open(path, "r", errors="ignore") as fh:
            for _ in range(head_lines):
                line = fh.readline()
                if not line:
                    break
                head.append(line)
        with open(path, "rb") as fh:
            fh.seek(0, os.SEEK_END)
            fh.seek(max(0, fh.tell() - tail_bytes))
            tail = fh.read().decode("utf-8", "ignore").splitlines()[1:]
    except OSError:
        return {"first": "", "last": ""}
    first = extract_topic(head, strict=True)["first"] or extract_topic(head)["first"]
    # Tail first, then head, then anything at all - never print harness noise as a topic.
    last = (extract_topic(tail, strict=True)["last"]
            or extract_topic(head, strict=True)["last"]
            or first
            or extract_topic(tail)["last"])
    return {"first": first, "last": last}


def ps_snapshot():
    try:
        return subprocess.run(
            ["ps", "-eo", "pid,ppid,command"], capture_output=True, text=True, timeout=20
        ).stdout
    except (OSError, subprocess.SubprocessError):
        return ""


def agents_json():
    exe = shutil.which("claude")
    if not exe:
        return "[]"
    try:
        return subprocess.run(
            [exe, "agents", "--json"], capture_output=True, text=True, timeout=30
        ).stdout
    except (OSError, subprocess.SubprocessError):
        return "[]"


# -------------------------------------------------------------------- assemble

def collect():
    sessions = parse_sessions(agents_json())
    ps_out = ps_snapshot()
    ids = [s.get("sessionId", "") for s in sessions]
    orphans = attribute_orphans(ps_out, ids)
    rows = []
    for s in sessions:
        sid = s.get("sessionId", "")
        head, tail, mtime = read_windows(sid)
        first = extract_topic(head, strict=True)["first"] or extract_topic(head)["first"]
        last = (extract_topic(tail, strict=True)["last"]
                or extract_topic(head, strict=True)["last"] or first
                or extract_topic(tail)["last"])
        title = extract_title(tail) or extract_title(head)
        rows.append({
            "project": project_of(s.get("cwd", "")),
            "status": s.get("status", "?"),
            "waitingFor": s.get("waitingFor", ""),
            "name": s.get("name", "?"),
            "title": title,
            "doing": extract_doing(tail),
            "since": since(mtime),
            "topic": last,
            "first": first,
            "age": age(s.get("startedAt")),
            "orphans": orphans.get(sid, 0),
            "pid": s.get("pid"),
            "sessionId": sid,
            "cwd": s.get("cwd", ""),
        })
    rows.sort(key=sort_key)
    return rows, count_orphans(ps_out, home=os.path.expanduser("~"))


# --------------------------------------------------------------------- display

_C = {"waiting": "\033[33;1m", "busy": "\033[36m", "idle": "\033[2m",
      "shell": "\033[35m", "reset": "\033[0m", "dim": "\033[2m", "bold": "\033[1m"}


def _paint(text, key, color):
    return f"{_C.get(key, '')}{text}{_C['reset']}" if color else text


def render(rows, total_orphans, color=True, width=None, show_prompt=False):
    if not rows:
        return "no Claude Code sessions found\n"
    width = width or shutil.get_terminal_size((150, 24)).columns
    w_proj = min(13, max(len(r["project"]) for r in rows))
    fixed = w_proj + 12 + 7 + 6
    w_title = max(18, min(34, (width - fixed) // 2))
    w_doing = max(18, width - fixed - w_title)

    counts = {}
    for r in rows:
        counts[r["status"]] = counts.get(r["status"], 0) + 1
    summary = " · ".join(f"{n} {s}" for s, n in sorted(counts.items(), key=lambda kv: _RANK.get(kv[0], 9)))

    out = [_paint(f"{len(rows)} sessions: {summary}", "bold", color)]
    if total_orphans:
        out.append(_paint(f"{total_orphans} detached processes under your home on PID 1", "dim", color))
    gates = gate_line()
    if gates:
        out.append(_paint(gates, "busy", color))
    out.append("")

    for r in rows:
        label = "NEEDS YOU" if r["status"] == "waiting" else r["status"]
        title = r["title"] or r["name"]
        doing = r["doing"] or "-"
        line = (f"{r['project']:<{w_proj}}  {_paint(f'{label:<10}', r['status'], color)}  "
                f"{truncate(title, w_title):<{w_title}}  "
                f"{_paint(truncate(doing, w_doing), 'dim', color)}"
                f"{' ' * max(0, w_doing - len(truncate(doing, w_doing)))}  "
                f"{r['since']:>5}")
        if r["orphans"]:
            line += _paint(f"  +{r['orphans']} detached", "waiting", color)
        out.append(line)
        if show_prompt and r["topic"]:
            out.append(_paint(f"{' ' * (w_proj + 14)}\u21b3 {truncate(r['topic'], width - w_proj - 18)}", "dim", color))
    return "\n".join(out) + "\n"


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    rows, total_orphans = collect()
    if "--json" in argv:
        print(json.dumps(rows, indent=2))
        return 0
    if "--blocked" in argv:
        rows = [r for r in rows if r["status"] == "waiting" or r["orphans"]]
    color = sys.stdout.isatty() and "NO_COLOR" not in os.environ and "--no-color" not in argv
    sys.stdout.write(render(rows, total_orphans, color=color))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
