#!/usr/bin/env python3
"""ccwho engine - all the logic. HOT-RELOADED by the runner on every tick.

Keep this module free of long-lived objects: the runner calls importlib.reload()
each iteration so edits land in a running watch without restarting it. Only pure
functions and plain dicts cross the boundary; state lives in the runner and is
passed back in, the way network_check_ruby carries @options between ticks.

Reads only what Claude Code already writes to disk. No daemon, no hooks, no tmux.

  claude agents --json      -> name, cwd, status, waitingFor, pid, sessionId
  ~/.claude/projects/**/    -> <sessionId>.jsonl transcript, for the real topic
  ps                        -> processes reparented to PID 1, matched by sessionId
"""
from __future__ import annotations

import glob
import json
import os
import datetime
import re
import shutil
import subprocess
import sys
import time

# Status order: what needs you first, what is working next, what is parked last.
# stopped outranks busy: a stopped session will not progress without you, while a
# busy one is fine. `running` is not busy but has background work in flight - it is
# waiting on a machine, not on you, so it sorts last.
_RANK = {"blocked": 0, "waiting": 0, "asks": 1, "stopped": 2, "busy": 3,
         "ready": 4, "shell": 5, "idle": 6, "running": 7}

# Descendants that are session infrastructure rather than work. An idle session
# keeps its MCP servers alive; counting them would make every session look busy.
_INFRA = re.compile(r"(npm exec\s+\S*mcp|\S*-mcp\b|mcp-server|mcp_server)|_npx/", re.I)

# Closing-line requests that hand the decision back without a question mark.
# Deliberately short: every entry was validated against a live fleet, and a false
# positive costs a glance while a false negative loses the session entirely.
_ASK_PHRASES = ("tell me", "let me know", "your call", "say the word",
                "which do you want", "shall i", "want me to", "should i",
                "do you want", "confirm whether")
_UNKNOWN_RANK = 4


# ---------------------------------------------------------------- pure helpers

def parse_sessions(raw):
    """Parse `claude agents --json`. A broken feed is empty, never an exception."""
    try:
        data = json.loads(raw)
    except (ValueError, TypeError):
        return []
    return data if isinstance(data, list) else []


def project_of(cwd):
    """Repo name for a cwd. A worktree reports its parent repo, not the branch dir."""
    if not cwd:
        return "?"
    parts = [p for p in cwd.split("/") if p]
    if not parts:
        return "?"
    for marker in (".claude", ".git"):
        if marker in parts:
            i = parts.index(marker)
            if i > 0:
                return parts[i - 1]
    return parts[-1]


def _text_of(content):
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        return " ".join(
            b.get("text", "") for b in content if isinstance(b, dict) and b.get("type") == "text"
        )
    return ""


# Prompts the harness injects as "user" turns. They are never what the session is about.
_BOILERPLATE = (
    "Base directory for this skill:",
    "This session is being continued from a previous conversation",
    "Caveat: The messages below were generated by the user",
    "<",
)


def is_boilerplate(text):
    return text.startswith(_BOILERPLATE)


def extract_topic(lines, strict=False):
    """First and last real user prompt. Skips tool noise and system reminders."""
    real, any_prompt = [], []
    for d in as_records(lines):
        if d.get("type") != "user":
            continue
        text = " ".join(_text_of(d.get("message", {}).get("content")).split())
        if not text:
            continue
        any_prompt.append(text)
        if not is_boilerplate(text):
            real.append(text)
    # Prefer a genuine prompt. In strict mode report nothing rather than harness noise,
    # so the caller can widen its search window instead of printing a task-notification.
    if strict:
        pool = real
    else:
        pool = real or [t for t in any_prompt if not t.startswith("<")] or any_prompt
    return {"first": pool[0] if pool else "", "last": pool[-1] if pool else ""}


def as_records(lines):
    """Accept raw JSONL strings or already-parsed dicts. Parsing a tail once per
    tick instead of once per extractor was a 5x cut; the extractors took 5.2
    passes over every line."""
    out = []
    for item in lines or ():
        if isinstance(item, dict):
            out.append(item)
            continue
        if not isinstance(item, str):
            continue
        try:
            d = json.loads(item)
        except (ValueError, TypeError):
            continue
        if isinstance(d, dict):
            out.append(d)
    return out


def cache_valid(entry, mtime, size):
    """A cached window is reusable only while the file is byte-for-byte unchanged."""
    if not isinstance(entry, dict):
        return False
    return entry.get("mtime") == mtime and entry.get("size") == size


def extract_title(lines):
    """Claude Code's own generated session title (`ai-title` entries)."""
    title = ""
    for d in as_records(lines):
        if d.get("type") == "ai-title" and d.get("aiTitle"):
            title = str(d["aiTitle"]).strip()
    return title


# Tools whose most useful hint is the file they touch.
_FILE_TOOLS = ("Edit", "Read", "Write", "NotebookEdit")


def _tool_hint(name, inp):
    if name == "Bash":
        return inp.get("description") or inp.get("command") or ""
    if name in _FILE_TOOLS:
        return os.path.basename(inp.get("file_path") or "")
    return inp.get("pattern") or inp.get("description") or inp.get("query") or ""


def extract_doing(lines):
    """What the session last actually did - the final tool call, human-readable."""
    doing = ""
    for d in as_records(lines):
        if d.get("type") != "assistant":
            continue
        content = d.get("message", {}).get("content")
        if not isinstance(content, list):
            continue
        for b in content:
            if isinstance(b, dict) and b.get("type") == "tool_use":
                name = b.get("name", "?")
                hint = " ".join(str(_tool_hint(name, b.get("input", {}) or {})).split())
                doing = f"{name}: {hint}" if hint else name
    return doing


# Only real turns. Idle transcripts keep receiving metadata writes (atis-latch,
# bridge-session, mode), so file mtime says "4m" for a session last worked six days
# ago - wrong on exactly the parked sessions where recency matters.
_TURN_TYPES = ("assistant", "user")


def last_turn_ts(lines):
    """Epoch seconds of the last real turn, from its `timestamp` field."""
    latest = None
    for d in as_records(lines):
        if d.get("type") not in _TURN_TYPES:
            continue
        raw = d.get("timestamp")
        if not raw:
            continue
        try:
            latest = datetime.datetime.fromisoformat(
                str(raw).replace("Z", "+00:00")).timestamp()
        except (ValueError, TypeError):
            continue
    return latest


def since(mtime, now=None):
    """Time since last transcript write - real activity, unlike session start age."""
    if mtime is None or not isinstance(mtime, (int, float)):
        return "?"
    secs = max(0, int((time.time() if now is None else now) - mtime))
    if secs < 60:
        return f"{secs}s"
    if secs < 3600:
        return f"{secs // 60}m"
    if secs < 86400:
        return f"{secs // 3600}h"
    return f"{secs // 86400}d"


def attribute_orphans(ps_output, session_ids):
    """Map sessionId -> count of processes reparented to PID 1 whose cmdline names it.

    This is the detached-work blind spot: work a session launched with `&` or nohup
    outlives it, is adopted by PID 1, and the session then reports idle.
    """
    counts = {sid: 0 for sid in session_ids}
    for pid, ppid, cmd in _ps_rows(ps_output):
        if ppid != 1:
            continue
        for sid in session_ids:
            if sid and sid in cmd:
                counts[sid] += 1
    return counts


def count_orphans(ps_output, home=None):
    """Orphans reparented to PID 1. With `home`, count only work under it -
    macOS has hundreds of system daemons on PID 1 and none of them are yours."""
    total = 0
    for _pid, ppid, cmd in _ps_rows(ps_output):
        if ppid != 1:
            continue
        if home and home not in cmd:
            continue
        total += 1
    return total


def _ps_rows(ps_output):
    for line in (ps_output or "").splitlines():
        fields = line.strip().split(None, 2)
        if len(fields) < 3 or not fields[1].isdigit():
            continue
        yield fields[0], int(fields[1]), fields[2]


def _closing_line(text):
    lines = [ln.strip() for ln in (text or "").splitlines() if ln.strip()]
    if not lines:
        return ""
    return re.sub(r"[*_`#>]", "", lines[-1]).strip()


def asks_user(text):
    """Does this message hand the decision back to the human?

    The harness reports `idle` for a session that ended its turn with a question,
    so status alone loses them. Only the closing line is considered: a question
    earlier in a long report is usually one the message goes on to answer.
    """
    closing = _closing_line(text).lower()
    if not closing:
        return False
    return "?" in closing or any(p in closing for p in _ASK_PHRASES)


def last_assistant_text(lines):
    text = ""
    for d in as_records(lines):
        if d.get("type") != "assistant":
            continue
        content = d.get("message", {}).get("content")
        if isinstance(content, list):
            for b in content:
                if isinstance(b, dict) and b.get("type") == "text" and b.get("text", "").strip():
                    text = b["text"]
    return text


def extract_ask(lines):
    """The closing line, when it is a request. Empty when the session is not asking."""
    text = last_assistant_text(lines)
    return _closing_line(text) if asks_user(text) else ""


def waiting_kind(lines):
    """Split Claude Code's `waiting` into what it actually means.

    `waitingFor: "input needed"` covers two very different states: a session
    genuinely blocked on a permission prompt or question, and one that simply
    finished its turn and is sitting at the prompt. Only the first needs you.
    The tell is an unanswered tool_use - a tool call with no matching tool_result.
    """
    pending = set()
    for d in as_records(lines):
        content = d.get("message", {}).get("content")
        if not isinstance(content, list):
            continue
        if d.get("type") == "assistant":
            for b in content:
                if isinstance(b, dict) and b.get("type") == "tool_use":
                    pending.add(b.get("id"))
        elif d.get("type") == "user":
            for b in content:
                if isinstance(b, dict) and b.get("type") == "tool_result":
                    pending.discard(b.get("tool_use_id"))
    return "blocked" if pending else "ready"


def gate_line(gate_dir=None):
    """One line naming who currently holds a ccgate slot, if anyone does."""
    try:
        import ccgate
    except ImportError:
        return ""
    gate_dir = gate_dir if gate_dir is not None else ccgate.GATE_DIR
    held = [h for h in ccgate.gate_status(gate_dir) if h.get("alive", True)]
    if not held:
        return ""
    who = ", ".join(f"{h.get('label') or '?'}({int(time.time() - h.get('since', time.time()))}s)"
                    for h in held)
    return f"{len(held)} gate slot(s) held: {who}"


def work_descendants(ps_output, pid):
    """How many non-infrastructure processes this session has running under it.

    Zero means the session has stopped: nothing is in flight, so it will not move
    again without you. Non-zero means it is waiting on a machine, not on a human.
    """
    if not pid:
        return 0
    kids = {}
    for cpid, ppid, cmd in _ps_rows(ps_output):
        try:
            kids.setdefault(ppid, []).append((int(cpid), cmd))
        except (TypeError, ValueError):
            continue
    count, stack, seen = 0, [int(pid)], {int(pid)}
    while stack:
        for cpid, cmd in kids.get(stack.pop(), []):
            if cpid in seen:
                continue
            seen.add(cpid)
            stack.append(cpid)
            if not _INFRA.search(cmd):
                count += 1
    return count


def sort_key(row):
    """Rank first, then most-recent-first so a fresh ask surfaces above parked ones."""
    key = row.get("attention") or row.get("status")
    ts = row.get("ts")
    return (_RANK.get(key, _UNKNOWN_RANK), -(ts if ts is not None else 0),
            row.get("project", ""), row.get("name", ""))


def age(started_ms, now=None):
    # `not started_ms` would swallow epoch 0, which is a valid timestamp.
    if started_ms is None or not isinstance(started_ms, (int, float)):
        return "?"
    now = int(time.time() * 1000) if now is None else now
    mins = max(0, (now - started_ms) // 60000)
    if mins < 60:
        return f"{mins}m"
    if mins < 1440:
        return f"{mins // 60}h"
    return f"{mins // 1440}d"


def truncate(s, width):
    s = s or ""
    return s if len(s) <= width else s[: max(0, width - 1)] + "…"


# ------------------------------------------------------------------ disk reads

def transcript_path(session_id):
    if not session_id:
        return None
    hits = glob.glob(os.path.expanduser(f"~/.claude/projects/*/{session_id}.jsonl"))
    return hits[0] if hits else None


def read_windows(session_id, tail_bytes=1024 * 1024, head_lines=400, cache=None):
    """Head and tail of a transcript as PARSED records, plus its mtime.

    `cache` is owned by the runner (it survives hot reload) and keyed on
    sessionId, holding (mtime, size). An unchanged transcript is not re-read or
    re-parsed - which is most of them, most ticks.
    """
    path = transcript_path(session_id)
    if not path:
        return [], [], None
    try:
        st = os.stat(path)
    except OSError:
        return [], [], None
    if cache is not None:
        hit = cache.get(session_id)
        if cache_valid(hit, st.st_mtime, st.st_size):
            return hit["head"], hit["tail"], hit["mtime"]
    try:
        head = []
        with open(path, "r", errors="ignore") as fh:
            for _ in range(head_lines):
                line = fh.readline()
                if not line:
                    break
                head.append(line)
        with open(path, "rb") as fh:
            fh.seek(0, os.SEEK_END)
            fh.seek(max(0, fh.tell() - tail_bytes))
            tail = fh.read().decode("utf-8", "ignore").splitlines()[1:]
        head, tail = as_records(head), as_records(tail)
        if cache is not None:
            cache[session_id] = {"mtime": st.st_mtime, "size": st.st_size,
                                 "head": head, "tail": tail}
        return head, tail, st.st_mtime
    except OSError:
        return [], [], None


def topic_for(session_id, tail_bytes=4 * 1024 * 1024, head_lines=400):
    """Head+tail read only. Transcripts reach hundreds of MB; never read the whole file."""
    path = transcript_path(session_id)
    if not path:
        return {"first": "", "last": ""}
    try:
        head = []
        with open(path, "r", errors="ignore") as fh:
            for _ in range(head_lines):
                line = fh.readline()
                if not line:
                    break
                head.append(line)
        with open(path, "rb") as fh:
            fh.seek(0, os.SEEK_END)
            fh.seek(max(0, fh.tell() - tail_bytes))
            tail = fh.read().decode("utf-8", "ignore").splitlines()[1:]
    except OSError:
        return {"first": "", "last": ""}
    first = extract_topic(head, strict=True)["first"] or extract_topic(head)["first"]
    # Tail first, then head, then anything at all - never print harness noise as a topic.
    last = (extract_topic(tail, strict=True)["last"]
            or extract_topic(head, strict=True)["last"]
            or first
            or extract_topic(tail)["last"])
    return {"first": first, "last": last}


def parse_tty_map(ps_output):
    """pid -> controlling terminal. `??` means no terminal, so it is omitted."""
    out = {}
    for line in (ps_output or "").splitlines():
        f = line.strip().split()
        if len(f) < 2 or not f[0].isdigit():
            continue
        if f[1] in ("??", "?", "-"):
            continue
        out[int(f[0])] = f[1]
    return out


_ANSI = re.compile(r"\033(?:\][^\007\033]*(?:\007|\033\\)|\[[0-9;]*[A-Za-z])")
# A jump target is a tty like s032 or a bare pid. Nothing else is accepted, so a
# crafted URL cannot smuggle anything into the handler.
_JUMP_TARGET = re.compile(r"^[A-Za-z]?[0-9]{1,8}$")


def visible_len(text):
    """Length as rendered: escape sequences occupy no columns."""
    return len(_ANSI.sub("", text or ""))


def osc8(label, url, enabled=True):
    """Wrap a label as an OSC 8 hyperlink. iTerm2 renders it clickable."""
    if not enabled or not url:
        return label
    return f"\033]8;;{url}\033\\{label}\033]8;;\033\\"


def jump_url(row):
    target = short_tty(row.get("tty", "")) or (str(row.get("pid")) if row.get("pid") else "")
    return f"ccwho://jump/{target}" if target else ""


def parse_jump_url(url):
    """Extract the target from ccwho://jump/<target>, or "" if it is not one."""
    if not isinstance(url, str) or not url.startswith("ccwho://jump/"):
        return ""
    target = url[len("ccwho://jump/"):].strip().rstrip("/")
    return target if _JUMP_TARGET.match(target) else ""


def short_tty(tty):
    """ttys032 -> s032. Short enough for a column, still unambiguous."""
    t = (tty or "").rsplit("/", 1)[-1]
    return t[3:] if t.startswith("tty") and len(t) > 3 else t


def match_rows(rows, query):
    """Rows matching a pid, a tty (long or short), or a title/project substring."""
    q = (query or "").strip().lower()
    if not q:
        return []
    hits = []
    for r in rows:
        if q == str(r.get("pid")) or q in (r.get("tty", ""), short_tty(r.get("tty", ""))):
            hits.append(r)
        elif q in (r.get("title") or "").lower() or q in (r.get("project") or "").lower():
            hits.append(r)
    return hits


def tty_snapshot():
    try:
        return subprocess.run(["ps", "-eo", "pid,tty"], capture_output=True,
                              text=True, timeout=20).stdout
    except (OSError, subprocess.SubprocessError):
        return ""


def ps_snapshot():
    try:
        return subprocess.run(
            ["ps", "-eo", "pid,ppid,command"], capture_output=True, text=True, timeout=20
        ).stdout
    except (OSError, subprocess.SubprocessError):
        return ""


def agents_json():
    exe = shutil.which("claude")
    if not exe:
        return "[]"
    try:
        return subprocess.run(
            [exe, "agents", "--json"], capture_output=True, text=True, timeout=30
        ).stdout
    except (OSError, subprocess.SubprocessError):
        return "[]"


# -------------------------------------------------------------------- assemble

def build_row(session, head, tail, mtime, now=None, orphan_count=0, work=0, tty=""):
    """One display row from one session's data. Pure: no disk, no subprocess.

    collect() used to inline this, which hid the wiring - notably which clock
    `since` reads from - behind functions that only run against a live machine.
    """
    first = extract_topic(head, strict=True)["first"] or extract_topic(head)["first"]
    last = (extract_topic(tail, strict=True)["last"]
            or extract_topic(head, strict=True)["last"] or first
            or extract_topic(tail)["last"])
    status = session.get("status", "?")
    ask = extract_ask(tail)
    if status == "waiting":
        attention = waiting_kind(tail)
        if attention == "ready":
            # not a state of its own: decided like any other non-busy session
            attention = "asks" if ask else ("running" if work else "stopped")
    elif status != "busy" and ask:
        attention = "asks"
    elif status == "busy":
        attention = "busy"
    else:
        # Not busy and not asking: either it stopped, or it is waiting on work.
        attention = "running" if work else "stopped"
    ts = last_turn_ts(tail)
    return {
        "project": project_of(session.get("cwd", "")),
        "status": status,
        "attention": attention,
        "waitingFor": session.get("waitingFor", ""),
        "name": session.get("name", "?"),
        "title": extract_title(tail) or extract_title(head),
        "doing": extract_doing(tail),
        "ask": ask,
        "since": since(ts if ts is not None else mtime, now=now),
        "ts": ts,
        "topic": last,
        "first": first,
        "age": age(session.get("startedAt"), now=None if now is None else int(now * 1000)),
        "orphans": orphan_count,
        "work": work,
        "tty": tty,
        "pid": session.get("pid"),
        "sessionId": session.get("sessionId", ""),
        "cwd": session.get("cwd", ""),
    }


def collect(cache=None):
    sessions = parse_sessions(agents_json())
    ps_out = ps_snapshot()
    ttys = parse_tty_map(tty_snapshot())
    ids = [s.get("sessionId", "") for s in sessions]
    orphans = attribute_orphans(ps_out, ids)
    rows = []
    for s in sessions:
        sid = s.get("sessionId", "")
        head, tail, mtime = read_windows(sid, cache=cache)
        rows.append(build_row(s, head, tail, mtime, orphan_count=orphans.get(sid, 0),
                              work=work_descendants(ps_out, s.get("pid")),
                              tty=ttys.get(s.get("pid"), "")))
    rows.sort(key=sort_key)
    if cache is not None:                       # drop rows for sessions that ended
        for gone in set(cache) - set(ids):
            cache.pop(gone, None)
    return rows, count_orphans(ps_out, home=os.path.expanduser("~"))


# --------------------------------------------------------------------- display

_C = {"blocked": "\033[33;1m", "asks": "\033[35;1m", "stopped": "\033[33m",
      "running": "\033[2m", "ready": "\033[33m", "waiting": "\033[33;1m",
      "busy": "\033[36m", "idle": "\033[2m",
      "shell": "\033[35m", "reset": "\033[0m", "dim": "\033[2m", "bold": "\033[1m"}


def _paint(text, key, color):
    return f"{_C.get(key, '')}{text}{_C['reset']}" if color else text


def render(rows, total_orphans, color=True, width=None, show_prompt=False, links=False):
    if not rows:
        return "no Claude Code sessions found\n"
    width = width or shutil.get_terminal_size((150, 24)).columns
    w_proj = min(13, max(len(r["project"]) for r in rows))
    w_tty = max(4, min(7, max(len(short_tty(r.get("tty", ""))) for r in rows)))
    fixed = w_proj + w_tty + 14 + 7 + 6
    w_title = max(18, min(34, (width - fixed) // 2))
    w_doing = max(18, width - fixed - w_title)

    counts = {}
    for r in rows:
        k = r.get("attention") or r["status"]
        counts[k] = counts.get(k, 0) + 1
    summary = " · ".join(f"{n} {s}" for s, n in sorted(counts.items(), key=lambda kv: _RANK.get(kv[0], 9)))

    out = [_paint(f"{len(rows)} sessions: {summary}", "bold", color)]
    if total_orphans:
        out.append(_paint(f"{total_orphans} detached processes under your home on PID 1", "dim", color))
    gates = gate_line()
    if gates:
        out.append(_paint(gates, "busy", color))
    out.append("")

    for r in rows:
        att = r.get("attention") or r["status"]
        label = {"blocked": "NEEDS YOU", "asks": "ASKED YOU",
                 "stopped": "STOPPED", "ready": "stopped"}.get(att, att)
        title = r["title"] or r["name"]
        doing = (r.get("ask") if att == "asks" else r["doing"]) or "-"
        if att == "running" and r.get("work"):
            doing = f"[{r['work']} bg] {doing}"
        where = short_tty(r.get("tty", "")) or "-"
        where_cell = _paint(f"{where:<{w_tty}}", "dim", color)
        where_cell = osc8(where_cell, jump_url(r), enabled=links and where != "-")
        shown_doing = truncate(doing, w_doing)
        line = (f"{r['project']:<{w_proj}}  "
                f"{where_cell}  "
                f"{_paint(f'{label:<10}', att, color)}  "
                f"{truncate(title, w_title):<{w_title}}  "
                f"{_paint(shown_doing, 'dim', color)}"
                f"{' ' * max(0, w_doing - len(shown_doing))}  "
                f"{r['since']:>5}")
        if r["orphans"]:
            line += _paint(f"  +{r['orphans']} detached", "waiting", color)
        out.append(line)
        if show_prompt and r["topic"]:
            out.append(_paint(f"{' ' * (w_proj + w_tty + 16)}\u21b3 {truncate(r['topic'], width - w_proj - 18)}", "dim", color))
    return "\n".join(out) + "\n"


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    rows, total_orphans = collect()
    if "--json" in argv:
        print(json.dumps(rows, indent=2))
        return 0
    if "--blocked" in argv:
        rows = [r for r in rows if r["status"] == "waiting" or r["orphans"]]
    color = sys.stdout.isatty() and "NO_COLOR" not in os.environ and "--no-color" not in argv
    sys.stdout.write(render(rows, total_orphans, color=color))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
