#!/usr/bin/env python3
"""What a session was working on. Pure: no disk, no subprocess, no clock.

Everything here answers one question - "is this the session I am looking for?" -
from records the harness already wrote. It is split out from the engine because
the engine reaches the world (ps, osascript, `claude agents`) and this does not,
which is what makes these rules cheap to test against real transcript shapes.

The centre of it is the RECAP. Claude Code writes one into the transcript itself
as `{"type":"system","subtype":"away_summary","content":…,"timestamp":…}`, so the
best answer to "what was this about" costs nothing to obtain. Measured on a live
fleet on 2026-09-18: 14 of 15 sessions had one, 161 across the 40 newest
transcripts. They also go stale - one session's newest recap was 2 days and 23
turns old - so a recap is never shown without its age and the turns since it.
"""
from __future__ import annotations

import os
import re

import ccwho_procs as procs

# Text the harness puts in a "user" turn that you did not type. Prefixes, not
# substrings: a prompt that QUOTES one of these ("the log says 'Your claude.ai
# usage limit has reset' - can you check?") is still your prompt.
MACHINE_PREFIXES = (
    "Another Claude session sent a message",
    "<",                                  # agent-message, cross-session-message, reminders
    "Your claude.ai usage limit has reset",
    "[Subagent report]",
    "Base directory for this skill:",
    "This session is being continued from a previous conversation",
    "Caveat: The messages below were generated by the user",
)

# Yours, but they identify nothing: every parked session looks the same through
# them. They are skipped when looking for what a session is ABOUT, never treated
# as machine noise.
LOW_SIGNAL = {
    "continue", "go ahead", "go", "yes", "y", "ok", "okay", "sure", "do it",
    "carry on", "proceed", "next", "please continue", "keep going", "/compact",
    "/clear", "thanks", "ty",
}

MAX_PROGRESS = 5
_FILE_TOOLS = ("Edit", "Read", "Write", "NotebookEdit")


_COMMAND_NAME = re.compile(r"<command-name>\s*(/[\w:-]+)\s*</command-name>")
_COMMAND_ARGS = re.compile(r"<command-args>\s*(.*?)\s*</command-args>", re.S)


def command_of(text):
    """The slash command you typed, or "" - `/land`, `/review the gate flake`.

    Claude Code records a slash command as tags, so the "starts with <" rule read
    `/land` as harness noise and the brief then showed an OLDER prompt as the last
    thing you said. 55 of these across the 40 newest transcripts.
    """
    if not text:
        return ""
    m = _COMMAND_NAME.search(text)
    if not m:
        return ""
    args = _COMMAND_ARGS.search(text)
    arg = " ".join((args.group(1) if args else "").split())
    return f"{m.group(1)} {arg}".strip()


def project_of(cwd):
    """Repo name for a cwd. A worktree reports its parent repo, not the branch dir.

    Pure, and needed in two places: the live row (from `claude agents`) and the
    index (from the cwd every transcript record carries). Claude Code's own
    folder name is the path with slashes turned into dashes, so its last segment
    is a worktree's BRANCH - which is why the index cannot use it.
    """
    if not cwd:
        return "?"
    parts = [p for p in cwd.split("/") if p]
    if not parts:
        return "?"
    for marker in (".claude", ".git", ".wt"):
        if marker in parts:
            i = parts.index(marker)
            if i > 0:
                return parts[i - 1]
    return parts[-1]


def is_human_prompt(text):
    """Did a human type this, or did the harness put it there?"""
    if not text:
        return False
    if command_of(text):
        return True               # tags, but a command you typed
    return not text.strip().startswith(MACHINE_PREFIXES)


def is_substantive(text):
    """A human prompt that also SAYS something about this session."""
    if not is_human_prompt(text):
        return False
    text = (command_of(text) or text).strip()
    if text.startswith("/"):
        # A bare command is yours and says nothing about the work: "opened /model"
        # is not what a session is for. With arguments it carries the request.
        # (The text arrives either as tags or already extracted, so check both.)
        return bool(text.split(" ", 1)[1:] and text.split(" ", 1)[1].strip())
    return text.rstrip(".!").strip().lower() not in LOW_SIGNAL


def _text_of(content):
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        return " ".join(b.get("text", "") for b in content
                        if isinstance(b, dict) and b.get("type") == "text")
    return ""


def _prompt_text(rec):
    """A human prompt's text, or "" for anything else.

    A tool result is a "user" record too - the harness writes it, you did not say
    it - and it reads as "" here because its content blocks are `tool_result`, not
    `text`. Measured over the 25 newest transcripts: 8,966 tool-result records, 0
    of them carrying a text block as well. An explicit guard for that case was
    tried and deleted: no test could tell it apart from this line, which is the
    definition of code that is not doing anything.
    """
    if rec.get("type") != "user":
        return ""
    text = " ".join(_text_of(rec.get("message", {}).get("content")).split())
    return command_of(text) or text


def last_human_prompt(records):
    """The last thing YOU said, walking back past machine text and "continue".

    Falls back to the newest low-signal prompt rather than to nothing: "go ahead"
    is still true, and the recap carries the meaning in that case.
    """
    human, substantive = "", ""
    for rec in records or ():
        text = _prompt_text(rec)
        if not is_human_prompt(text):
            continue
        human = text
        if is_substantive(text):
            substantive = text
    return substantive or human


def first_human_prompt(records):
    """What you opened with - the closest thing to the session's brief."""
    for rec in records or ():
        text = _prompt_text(rec)
        if is_substantive(text):
            return text
    return ""


_RECAP_SUFFIX = "(disable recaps in /config)"


def recap(records):
    """The newest recap the harness wrote, and when. {"text": "", "ts": ""} if none."""
    out = {"text": "", "ts": ""}
    for rec in records or ():
        if rec.get("type") != "system" or rec.get("subtype") != "away_summary":
            continue
        text = " ".join(str(rec.get("content", "")).split())
        if text.endswith(_RECAP_SUFFIX):
            text = text[:-len(_RECAP_SUFFIX)].strip()
        ts = _ts(rec)
        # By age, not by position: the head window is read before the tail, so a
        # recap from days ago arrives FIRST. Position would make it the newest.
        if not out["text"] or ts >= out["ts"]:
            out = {"text": text, "ts": ts}
    return out


def _ts(rec):
    """A record's timestamp as a string. Transcripts are written by someone else:
    a missing or null timestamp is an unknown age, never a TypeError in the middle
    of rendering a list."""
    ts = rec.get("timestamp")
    return ts if isinstance(ts, str) else ""


def _is_synthetic(rec):
    """A message Claude Code wrote in the assistant's place, not the session.

    Limit notices, API errors, "No response requested." - all carry
    model "<synthetic>". Measured over the 40 newest transcripts: 43 of them, and
    without this every limited session's closing line reads "You've hit your
    session limit", which is identical across sessions and true of none of them.
    """
    return rec.get("message", {}).get("model") == "<synthetic>"


def _assistant_text(rec):
    """What the session said, or "" for a harness notice or a tool-only turn."""
    if rec.get("type") != "assistant" or _is_synthetic(rec):
        return ""
    return " ".join(_text_of(rec.get("message", {}).get("content")).split())


def _is_turn(rec):
    """A turn is conversation: something you said, or something it said back.
    Tool calls and their results are traffic, not turns - counting them would
    report "300 turns since the recap" for an afternoon of one task."""
    text = _prompt_text(rec)
    if text:
        return is_human_prompt(text)   # an agent-message is traffic, not conversation
    return bool(_assistant_text(rec))


def turns_since(records, ts):
    """How much conversation has happened since `ts`. 0 without a timestamp."""
    if not ts:
        return 0
    return sum(1 for rec in _unique(records)
               if _ts(rec) > ts and _is_turn(rec))


def _unique(records):
    """Records once each, in order. The engine reads a head window and a tail
    window and on a short transcript they are the same lines; a count that does
    not notice reports twice the conversation that happened."""
    seen, out = set(), []
    for rec in records or ():
        key = rec.get("uuid") or (rec.get("type"), _ts(rec),
                                  str(rec.get("content", ""))[:80],
                                  str(rec.get("message", {}))[:120])
        if key in seen:
            continue
        seen.add(key)
        out.append(rec)
    return out


def _tool_hint(name, inp):
    """One step, readable. The ONE copy: the list's `doing` column and the brief's
    progress both print it, to people and to agents - a Bash command without a
    description goes out as its short safe form. So does the rest: a description,
    a pattern or a query is text the model wrote, and it can hold what it was
    searching for."""
    if not isinstance(inp, dict):       # a transcript line of another shape
        return ""
    if name == "Bash":
        return (procs.safe_command(inp.get("description") or "", program=False)
                or procs.safe_command(inp.get("command") or ""))
    if name in _FILE_TOOLS:
        return procs.safe_command(os.path.basename(inp.get("file_path") or ""),
                                  program=False)
    return procs.safe_command(inp.get("pattern") or inp.get("description")
                              or inp.get("query") or "", program=False)


def progress(records, limit=MAX_PROGRESS):
    """The last `limit` DISTINCT steps, oldest first.

    Distinct matters: a session that retried one command four times has done one
    thing, and five identical lines say less than one line does.
    """
    steps = []
    for rec in records or ():
        if rec.get("type") != "assistant":
            continue
        content = rec.get("message", {}).get("content")
        if not isinstance(content, list):
            continue
        for b in content:
            if not (isinstance(b, dict) and b.get("type") == "tool_use"):
                continue
            name = b.get("name", "?")
            hint = " ".join(str(_tool_hint(name, b.get("input", {}) or {})).split())
            step = f"{name}: {hint}" if hint else name
            if not steps or steps[-1] != step:
                steps.append(step)
    return steps[-limit:]


def closing_line(records):
    """The last thing the session said to you - what it wants, if it wants anything."""
    last = ""
    for rec in records or ():
        text = _assistant_text(rec)
        if text:
            last = text
    return last


def title_of(records):
    """Claude Code's own generated session title (`ai-title` entries)."""
    title = ""
    for rec in records or ():
        if rec.get("type") == "ai-title" and rec.get("aiTitle"):
            title = str(rec["aiTitle"]).strip()
    return title


def short_id(session_id, width=4):
    """The first hex of the session id: the prefix of `claude --resume <id>` and of
    the transcript filename, so it links the other names without a lookup. Not the
    session's NAME - the name is the tab title, which is the one you can see."""
    return (session_id or "")[:width]


_AGE_UNITS = ((86400.0, "d"), (3600.0, "h"), (60.0, "m"))


def age_between(then, now):
    """Human age between two ISO timestamps. "" if either is missing or unparseable."""
    a, b = _epoch(then), _epoch(now)
    if a is None or b is None:
        return ""
    secs = max(0.0, b - a)
    for size, unit in _AGE_UNITS:
        if secs >= size:
            return f"{int(secs // size)}{unit}"
    return f"{int(secs)}s"


def _epoch(ts):
    """ISO-8601 with a Z to seconds. Deliberately tolerant: a transcript is
    written by someone else, and an unreadable timestamp is a missing age, never
    an exception in the middle of rendering a list."""
    if not ts or not isinstance(ts, str):
        return None
    try:
        import datetime
        return datetime.datetime.fromisoformat(ts.replace("Z", "+00:00")).timestamp()
    except (ValueError, TypeError):
        return None


def build(head, tail, session=None, now=None, as_records=None):
    """Everything needed to answer "is this the one?" without opening the session.

    `head` and `tail` are the windows the engine already reads (and caches) for
    every session, raw JSONL lines or parsed records. `as_records` lets the engine
    pass its own parser so a tick still parses each line exactly once.
    """
    session = session or {}
    parse = as_records or _as_records
    head_recs, tail_recs = parse(head), parse(tail)
    # The windows overlap on a short transcript, and there is a GAP between them on
    # a long one: the engine reads the first 400 lines and the last 1 MiB. So a
    # recap in the unread middle is invisible here, and counts are of what we read.
    # That is what the transcript index (R1.2b) exists to fix; until then, ordering
    # is by timestamp so at least nothing older outranks something newer.
    # Duplicates are harmless to every field that takes the newest or the last -
    # COUNTING is the one that cannot survive them, and turns_since() dedupes.
    both = head_recs + tail_recs
    r = recap(both)
    return {
        "title": title_of(both),
        "goal": first_human_prompt(head_recs) or first_human_prompt(both),
        "you_said": last_human_prompt(both),
        "recap": r["text"],
        "recap_ts": r["ts"],
        "recap_age": age_between(r["ts"], now) if now else "",
        "turns_since_recap": turns_since(both, r["ts"]),
        "progress": progress(tail_recs or both),
        "closing": closing_line(both),
        "aka": {
            "short_id": short_id(session.get("sessionId", "")),
            "session_id": session.get("sessionId", ""),
            "name": session.get("name", ""),
            "pid": session.get("pid"),
            "cwd": session.get("cwd", ""),
            "tty": session.get("tty", ""),
        },
    }


def _as_records(lines):
    """Fallback parser: the engine passes its own, which parses a tick once."""
    import json
    out = []
    for item in lines or ():
        if isinstance(item, dict):
            out.append(item)
        elif isinstance(item, str):
            try:
                d = json.loads(item)
            except (ValueError, TypeError):
                continue
            if isinstance(d, dict):
                out.append(d)
    return out
