"""Tests for ccwho_brief: what a session was working on. Stdlib only.

The fixtures here are the real shapes measured on a live fleet on 2026-09-18:
seven of fifteen sessions had a MACHINE message as their last "user" turn, and
fourteen of fifteen had a recap the harness had already written.

python3 -m unittest test_brief -v
"""
import json
import unittest

import ccwho_brief as brief


def user(text, ts="2026-09-18T10:00:00.000Z"):
    return {"type": "user", "timestamp": ts,
            "message": {"role": "user", "content": text}}


def assistant(text, ts="2026-09-18T10:01:00.000Z"):
    return {"type": "assistant", "timestamp": ts,
            "message": {"role": "assistant", "content": [{"type": "text", "text": text}]}}


def tool(name, inp, ts="2026-09-18T10:02:00.000Z"):
    return {"type": "assistant", "timestamp": ts,
            "message": {"role": "assistant",
                        "content": [{"type": "tool_use", "name": name, "input": inp}]}}


def tool_result(ts="2026-09-18T10:02:30.000Z"):
    return {"type": "user", "timestamp": ts,
            "message": {"role": "user",
                        "content": [{"type": "tool_result", "tool_use_id": "t1",
                                     "content": "ok"}]}}


def synthetic(text, ts="2026-09-18T23:40:00.000Z"):
    """What Claude Code itself writes into the assistant's place: limit notices,
    API errors, "No response requested." Measured over the 40 newest transcripts:
    43 of them, every one a harness notice, all carrying model "<synthetic>"."""
    return {"type": "assistant", "timestamp": ts,
            "message": {"role": "assistant", "model": "<synthetic>",
                        "content": [{"type": "text", "text": text}]}}


def recap_entry(text, ts="2026-09-16T10:18:00.000Z"):
    return {"type": "system", "subtype": "away_summary", "content": text,
            "timestamp": ts}


class TestIsHumanPrompt(unittest.TestCase):
    """The line that says "this is what you asked for" has to BE what you asked for.

    Measured on the live fleet: 7 of 15 sessions showed one of these instead.
    They are near-identical across sessions, so the column that should tell them
    apart made them look the same.
    """

    MACHINE = [
        'Another Claude session sent a message: <agent-message from="a256"> hello',
        "<agent-message from=\"abc\">do the thing</agent-message>",
        "<cross-session-message from=\"uds:/tmp/cc-socks/40.sock\">hi",
        "Your claude.ai usage limit has reset. Continue the task you were working on",
        "Base directory for this skill: /Users/x/.claude/skills/review",
        "This session is being continued from a previous conversation that ran out",
        "Caveat: The messages below were generated by the user while running local",
        "[Subagent report] the review found 3 issues",
    ]
    REAL = [
        "fix the gate flake in the timing suite",
        "yes, and also check whether main moved",
        "could you also run a research on grokbot",
    ]
    LOW_SIGNAL = ["continue", "go ahead", "yes", "ok", "/compact", "Continue.", " yes "]

    def test_machine_text_is_not_a_human_prompt(self):
        for t in self.MACHINE:
            self.assertFalse(brief.is_human_prompt(t), t[:40])

    def test_real_prompts_are_human_prompts(self):
        for t in self.REAL:
            self.assertTrue(brief.is_human_prompt(t), t[:40])

    def test_low_signal_prompts_are_human_but_not_substantive(self):
        for t in self.LOW_SIGNAL:
            self.assertTrue(brief.is_human_prompt(t), t)
            self.assertFalse(brief.is_substantive(t), t)

    def test_a_real_prompt_is_substantive(self):
        for t in self.REAL:
            self.assertTrue(brief.is_substantive(t), t[:40])

    def test_a_prompt_that_merely_mentions_a_machine_phrase_still_counts(self):
        # the test that keeps the rule a PREFIX rule, not a substring hunt
        t = "the log says 'Your claude.ai usage limit has reset' - can you check?"
        self.assertTrue(brief.is_human_prompt(t))


class TestLastHumanPrompt(unittest.TestCase):
    def test_it_walks_back_past_machine_text(self):
        recs = [user("rebase and land it"),
                user('Another Claude session sent a message: <agent-message from="a">go')]
        self.assertEqual(brief.last_human_prompt(recs), "rebase and land it")

    def test_it_walks_back_past_continue(self):
        recs = [user("fix the gate flake"), user("continue")]
        self.assertEqual(brief.last_human_prompt(recs), "fix the gate flake")

    def test_a_tool_result_is_not_a_prompt(self):
        recs = [user("fix the gate flake"), tool_result()]
        self.assertEqual(brief.last_human_prompt(recs), "fix the gate flake")

    def test_when_you_only_ever_said_continue_it_says_continue(self):
        # better than blank: it is still true, and the recap carries the meaning
        recs = [user("continue"), user("go ahead")]
        self.assertEqual(brief.last_human_prompt(recs), "go ahead")

    def test_nothing_human_at_all_is_empty(self):
        recs = [user("<agent-message>x"), tool_result()]
        self.assertEqual(brief.last_human_prompt(recs), "")

    def test_the_newest_substantive_prompt_wins(self):        # control
        recs = [user("old thing"), user("the new thing")]
        self.assertEqual(brief.last_human_prompt(recs), "the new thing")


class TestSlashCommands(unittest.TestCase):
    """`/land` is a thing you typed, not harness noise. It arrives wrapped in tags
    (55 of them across the 40 newest transcripts), so the prefix rule dropped it
    and the brief then showed an older prompt as "the last thing you said"."""

    LAND = "<command-message>land</command-message> <command-name>/land</command-name>"
    COMPACT = ("<command-name>/compact</command-name> <command-message>compact"
               "</command-message> <command-args></command-args>")
    WITH_ARGS = ("<command-message>review</command-message> <command-name>/review"
                 "</command-name> <command-args>the gate flake</command-args>")

    def test_a_slash_command_is_something_you_said(self):
        self.assertTrue(brief.is_human_prompt(self.LAND))
        self.assertEqual(brief.command_of(self.LAND), "/land")

    def test_it_reads_as_the_command_not_the_tags(self):
        # the tags never reach the screen: what you typed does
        self.assertEqual(brief.last_human_prompt([user(self.LAND)]), "/land")

    def test_a_command_with_arguments_is_what_you_last_said(self):
        recs = [user("fix the gate"), user(self.WITH_ARGS)]
        self.assertEqual(brief.last_human_prompt(recs), "/review the gate flake")

    def test_arguments_come_with_it(self):
        self.assertEqual(brief.command_of(self.WITH_ARGS), "/review the gate flake")

    def test_compact_is_still_low_signal(self):
        # it is yours, but it says nothing about what the session is FOR
        self.assertTrue(brief.is_human_prompt(self.COMPACT))
        self.assertFalse(brief.is_substantive(self.COMPACT))
        recs = [user("fix the gate"), user(self.COMPACT)]
        self.assertEqual(brief.last_human_prompt(recs), "fix the gate")

    def test_a_bare_command_says_nothing_about_the_work(self):
        # /model, /land, /clear: yours, but they do not identify the session, and
        # "opened /model" is not what this session is for
        bare = "<command-message>model</command-message> <command-name>/model</command-name>"
        self.assertTrue(brief.is_human_prompt(bare))
        self.assertFalse(brief.is_substantive(bare))
        recs = [user("fix the gate flake"), user(bare)]
        self.assertEqual(brief.last_human_prompt(recs), "fix the gate flake")

    def test_a_command_with_arguments_does_say_something(self):
        self.assertTrue(brief.is_substantive(self.WITH_ARGS))    # control

    def test_other_tagged_text_is_still_machine(self):      # control
        self.assertFalse(brief.is_human_prompt("<task-notification> <task-id>ab9</task-id>"))
        self.assertEqual(brief.command_of("<agent-message from=\"x\">hi"), "")


class TestRecap(unittest.TestCase):
    """Claude Code already writes a recap into the transcript
    (`{"type":"system","subtype":"away_summary"}`). Measured 2026-09-18: 14 of 15
    live sessions had one, 161 across the 40 newest transcripts. They go stale -
    one session's newest recap was two days and twenty-three turns old - so the
    age and the turns since are part of the answer, not decoration."""

    def test_the_newest_recap_wins(self):
        recs = [recap_entry("older", "2026-09-14T10:00:00.000Z"),
                recap_entry("newer", "2026-09-16T10:00:00.000Z")]
        got = brief.recap(recs)
        self.assertEqual(got["text"], "newer")
        self.assertEqual(got["ts"], "2026-09-16T10:00:00.000Z")

    def test_the_config_hint_is_not_part_of_the_recap(self):
        recs = [recap_entry("Goal: fix #362. (disable recaps in /config)")]
        self.assertEqual(brief.recap(recs)["text"], "Goal: fix #362.")

    def test_no_recap_is_empty_not_an_error(self):
        self.assertEqual(brief.recap([user("hi")]), {"text": "", "ts": ""})

    def test_turns_since_counts_conversation_not_tool_traffic(self):
        recs = [recap_entry("r", "2026-09-16T10:00:00.000Z"),
                tool("Bash", {"description": "run the gate"}, "2026-09-16T11:00:00.000Z"),
                tool_result("2026-09-16T11:00:30.000Z"),
                assistant("the gate is green", "2026-09-16T11:01:00.000Z"),
                user("land it", "2026-09-16T11:02:00.000Z")]
        self.assertEqual(brief.turns_since(recs, "2026-09-16T10:00:00.000Z"), 2)

    def test_turns_before_the_recap_do_not_count(self):
        recs = [user("early", "2026-09-15T09:00:00.000Z"),
                recap_entry("r", "2026-09-16T10:00:00.000Z"),
                user("after", "2026-09-16T10:30:00.000Z")]
        self.assertEqual(brief.turns_since(recs, "2026-09-16T10:00:00.000Z"), 1)

    def test_no_timestamp_means_no_count(self):
        self.assertEqual(brief.turns_since([user("x")], ""), 0)


class TestSyntheticMessagesAreNotTheSessionTalking(unittest.TestCase):
    """A session that hit its limit ends with "You've hit your session limit ·
    resets 11:40pm". Read as the closing line, every limited session looks like it
    is asking you the same thing, and the one that IS asking you something is
    buried. The harness marks these: model "<synthetic>"."""

    def test_the_closing_line_walks_back_past_a_limit_notice(self):
        recs = [assistant("Shall I land it?", "2026-09-18T15:48:00.000Z"),
                synthetic("You've hit your session limit · resets 11:40pm")]
        self.assertEqual(brief.closing_line(recs), "Shall I land it?")

    def test_a_synthetic_message_is_not_a_turn(self):
        recs = [recap_entry("r", "2026-09-16T10:00:00.000Z"),
                synthetic("API Error: 400 status code", "2026-09-16T11:00:00.000Z")]
        self.assertEqual(brief.turns_since(recs, "2026-09-16T10:00:00.000Z"), 0)

    def test_a_real_reply_after_a_notice_is_still_the_closing_line(self):   # control
        recs = [synthetic("You've hit your session limit", "2026-09-18T10:00:00.000Z"),
                assistant("back, and the gate is green", "2026-09-18T12:00:00.000Z")]
        self.assertEqual(brief.closing_line(recs), "back, and the gate is green")


class TestWindowsOverlapAndOddRecords(unittest.TestCase):
    """The engine reads a head window and a tail window; on a short transcript they
    are the SAME records. Anything that counts has to count a record once, and
    anything a transcript can contain has to be survivable - these files are
    written by someone else."""

    def test_a_record_in_both_windows_is_counted_once(self):
        recs = [recap_entry("r", "2026-09-16T10:00:00.000Z"),
                assistant("the gate is green", "2026-09-16T11:00:00.000Z")]
        b = brief.build(recs, recs, session={"sessionId": "abcd"})
        self.assertEqual(b["turns_since_recap"], 1)

    def test_a_uuid_identifies_a_record_across_windows(self):
        rec = dict(assistant("hi", "2026-09-16T11:00:00.000Z"), uuid="u1")
        recap = recap_entry("r", "2026-09-16T10:00:00.000Z")
        b = brief.build([recap, rec], [dict(rec)], session={"sessionId": "abcd"})
        self.assertEqual(b["turns_since_recap"], 1)

    def test_machine_text_is_not_conversation(self):
        recs = [recap_entry("r", "2026-09-16T10:00:00.000Z"),
                user("Another Claude session sent a message: do the thing",
                     "2026-09-16T11:00:00.000Z")]
        self.assertEqual(brief.turns_since(recs, "2026-09-16T10:00:00.000Z"), 0)

    def test_your_continue_is_still_conversation(self):        # control
        recs = [recap_entry("r", "2026-09-16T10:00:00.000Z"),
                user("continue", "2026-09-16T11:00:00.000Z")]
        self.assertEqual(brief.turns_since(recs, "2026-09-16T10:00:00.000Z"), 1)

    def test_a_null_timestamp_does_not_crash_the_brief(self):
        recs = [recap_entry("r", "2026-09-16T10:00:00.000Z"),
                {"type": "system", "subtype": "other", "timestamp": None},
                {"type": "user", "message": {"role": "user", "content": "hi"}}]
        self.assertEqual(brief.turns_since(recs, "2026-09-16T10:00:00.000Z"), 0)
        brief.build(recs, [], session={"sessionId": "abcd"})    # must not raise

    def test_the_newest_recap_wins_even_when_it_is_read_first(self):
        # head is read before tail, so position is not age: an old recap in the
        # head must not outrank a newer one, and vice versa
        old = recap_entry("older", "2026-09-14T10:00:00.000Z")
        new = recap_entry("newer", "2026-09-16T10:00:00.000Z")
        self.assertEqual(brief.recap([new, old])["text"], "newer")
        self.assertEqual(brief.recap([old, new])["text"], "newer")


class TestProgress(unittest.TestCase):
    def test_the_last_five_distinct_steps_newest_last(self):
        recs = [tool("Bash", {"description": f"step {i}"}) for i in range(1, 8)]
        got = brief.progress(recs)
        self.assertEqual(got, ["Bash: step 3", "Bash: step 4", "Bash: step 5",
                               "Bash: step 6", "Bash: step 7"])

    def test_a_repeated_step_is_not_five_lines_of_the_same_thing(self):
        recs = [tool("Bash", {"description": "run the gate"}) for _ in range(4)]
        recs.append(tool("Edit", {"file_path": "/x/y/engine.py"}))
        self.assertEqual(brief.progress(recs), ["Bash: run the gate", "Edit: engine.py"])

    def test_no_tools_yet_is_empty(self):
        self.assertEqual(brief.progress([user("hi")]), [])


class TestBuildBrief(unittest.TestCase):
    HEAD = [json.dumps(user("fix issue 362: the loop's memory bloat",
                            "2026-09-14T09:00:00.000Z"))]
    TAIL = [json.dumps(r) for r in [
        recap_entry("Goal: fix the loop's memory bloat (#362), now fully reviewed."
                    " (disable recaps in /config)", "2026-09-16T10:18:00.000Z"),
        tool("Bash", {"description": "Run the gate"}, "2026-09-18T15:40:00.000Z"),
        assistant("The gate is green.", "2026-09-18T15:45:00.000Z"),
        user("continue", "2026-09-18T15:47:00.000Z"),
        {"type": "ai-title", "aiTitle": "Issue 362"},
        assistant("Shall I land it?", "2026-09-18T15:48:00.000Z"),
    ]]

    def setUp(self):
        self.b = brief.build(self.HEAD, self.TAIL,
                             session={"sessionId": "6c4c20f6-c6fb-46e5-bc8a-699f013cbe69",
                                      "cwd": "/Users/x/projects/liveapp",
                                      "name": "liveapp-f0", "pid": 90266},
                             now="2026-09-18T16:18:00.000Z")

    def test_the_recap_leads_with_its_age_and_turns(self):
        self.assertIn("memory bloat", self.b["recap"])
        self.assertNotIn("disable recaps", self.b["recap"])
        self.assertEqual(self.b["recap_age"], "2d")
        self.assertEqual(self.b["turns_since_recap"], 3)

    def test_you_said_skips_continue_and_finds_the_real_prompt(self):
        self.assertEqual(self.b["you_said"], "fix issue 362: the loop's memory bloat")

    def test_the_goal_is_the_title_and_the_opening_prompt(self):
        self.assertEqual(self.b["title"], "Issue 362")
        self.assertEqual(self.b["goal"], "fix issue 362: the loop's memory bloat")

    def test_progress_is_there(self):
        self.assertEqual(self.b["progress"], ["Bash: Run the gate"])

    def test_the_closing_line_is_kept(self):
        self.assertEqual(self.b["closing"], "Shall I land it?")

    def test_it_carries_the_other_names_of_this_session(self):
        aka = self.b["aka"]
        self.assertEqual(aka["short_id"], "6c4c")
        self.assertEqual(aka["session_id"], "6c4c20f6-c6fb-46e5-bc8a-699f013cbe69")
        self.assertEqual(aka["name"], "liveapp-f0")
        self.assertEqual(aka["pid"], 90266)
        self.assertEqual(aka["cwd"], "/Users/x/projects/liveapp")

    def test_a_session_with_nothing_in_it_still_builds_a_brief(self):
        b = brief.build([], [], session={"sessionId": "abcd1234"})
        self.assertEqual(b["recap"], "")
        self.assertEqual(b["you_said"], "")
        self.assertEqual(b["progress"], [])
        self.assertEqual(b["aka"]["short_id"], "abcd")


if __name__ == "__main__":
    unittest.main()


class TestTheBriefNeverPrintsASecret(unittest.TestCase):
    """The brief's progress lines show a Bash call's command when it has no
    description, and `ccwho show` (text and --json) prints them to whoever
    asked - often an agent. One _tool_hint serves the brief and the list."""

    TOKEN = "sk-ant-FAKE-brief-must-never-print"

    def recs(self, command):
        return [{"type": "assistant", "message": {"content": [
            {"type": "tool_use", "name": "Bash", "input": {"command": command}}]}}]

    def test_a_token_in_a_command_is_masked(self):
        got = brief.progress(self.recs(f"curl -H 'Authorization: Bearer {self.TOKEN}' x"))
        self.assertNotIn(self.TOKEN, " ".join(got))

    def test_a_token_with_no_known_shape_is_not_shown(self):
        got = brief.progress(self.recs("deploy --stage prod k8Hq2vX9pLm3nR7tW1yZ4bC6dF0gJ5sA"))
        self.assertEqual(got, ["Bash: deploy --stage …"])

    def test_no_hint_carries_a_control_character(self):
        # a description, a pattern or a query is text the model wrote: it can
        # hold an escape sequence that retitles the window or repaints the list
        for name, inp in (("Bash", {"command": "x", "description": "a\x1b]0;t\x07b"}),
                          ("Grep", {"pattern": "a\x1b[2Jb"}),
                          ("WebSearch", {"query": "a\x9bb"})):
            with self.subTest(name=name):
                got = brief._tool_hint(name, inp)
                self.assertNotRegex(got, r"[\x00-\x1f\x7f-\x9f]")
                self.assertTrue(got)

    def test_no_hint_carries_a_token(self):
        for name, inp in (("Bash", {"command": "x", "description": f"use {self.TOKEN}"}),
                          ("Grep", {"pattern": self.TOKEN})):
            with self.subTest(name=name):
                self.assertNotIn(self.TOKEN, brief._tool_hint(name, inp))

    def test_what_the_model_wrote_is_shaped_too(self):
        # cycle 3 #12: a pattern, a query or a description is printed in the
        # default view, so it goes through the allowlist, not the blocklist
        for name, inp in (("Grep", {"pattern": "hunter2secret"}),
                          ("Bash", {"command": "x", "description": "Log in with db pass hunter2"}),
                          ("WebSearch", {"query": "token abcd1234efgh"})):
            with self.subTest(name=name):
                got = brief._tool_hint(name, inp)
                self.assertNotIn("hunter2", got)
                self.assertNotIn("abcd1234efgh", got)

    def test_plain_hints_stay_readable(self):                          # control
        self.assertEqual(brief._tool_hint("Grep", {"pattern": "def collect"}), "def collect")
        self.assertEqual(brief._tool_hint("Bash", {"command": "x",
                                                   "description": "Run the tests"}),
                         "Run the tests")

    def test_an_input_that_is_not_a_dict_does_not_crash(self):
        # review 6 #7: one such transcript line stopped ls, ps and the list
        for inp in ("x", [1], 5):
            with self.subTest(inp=inp):
                self.assertEqual(brief._tool_hint("Grep", inp), "")
        self.assertEqual(brief._tool_hint("Grep", {"pattern": "def x"}), "def x")  # control

    def test_a_hint_that_is_not_text_does_not_crash(self):
        # review 4 #3: a tool input of another type took collect() down with it
        for name, inp in (("Grep", {"pattern": 5}), ("Bash", {"command": ["ls"]}),
                          ("WebSearch", {"query": {"q": 1}})):
            with self.subTest(name=name):
                recs = [{"type": "assistant", "message": {"content": [
                    {"type": "tool_use", "name": name, "input": inp}]}}]
                self.assertIsInstance(brief.progress(recs), list)

    def test_a_plain_command_is_shown(self):                          # control
        self.assertEqual(brief.progress(self.recs("npm test")), ["Bash: npm test"])
