"""Tests for ccwho. Stdlib only: python3 -m unittest -v"""
import json
import os
import unittest

import ccwho_engine as ccwho


class TestParseSessions(unittest.TestCase):
    def test_parses_agents_json(self):
        raw = json.dumps([
            {"pid": 1, "cwd": "/Users/x/projects/liveapp", "kind": "interactive",
             "startedAt": 1000, "sessionId": "aaa", "name": "liveapp-4e", "status": "busy"},
        ])
        got = ccwho.parse_sessions(raw)
        self.assertEqual(len(got), 1)
        self.assertEqual(got[0]["name"], "liveapp-4e")

    def test_empty_input_is_not_an_error(self):
        self.assertEqual(ccwho.parse_sessions("[]"), [])

    def test_malformed_json_returns_empty(self):
        self.assertEqual(ccwho.parse_sessions("not json"), [])


class TestProject(unittest.TestCase):
    def test_project_is_last_path_component(self):
        self.assertEqual(ccwho.project_of("/Users/x/projects/liveapp"), "liveapp")

    def test_worktree_keeps_parent_repo_name(self):
        cwd = "/Users/x/projects/football/.claude/worktrees/fix-nav"
        self.assertEqual(ccwho.project_of(cwd), "football")

    def test_missing_cwd(self):
        self.assertEqual(ccwho.project_of(""), "?")


class TestTopic(unittest.TestCase):
    def _lines(self, *msgs):
        out = []
        for m in msgs:
            out.append(json.dumps({"type": "user", "message": {"content": m}}))
        return out

    def test_last_user_prompt_is_the_topic(self):
        got = ccwho.extract_topic(self._lines("first thing", "second thing"))
        self.assertEqual(got["last"], "second thing")
        self.assertEqual(got["first"], "first thing")

    def test_skips_system_reminders_and_tool_noise(self):
        got = ccwho.extract_topic(self._lines("real prompt", "<system-reminder>noise</>"))
        self.assertEqual(got["last"], "real prompt")

    def test_handles_content_as_block_list(self):
        line = json.dumps({"type": "user", "message": {"content": [
            {"type": "text", "text": "block prompt"},
            {"type": "tool_result", "content": "ignored"},
        ]}})
        self.assertEqual(ccwho.extract_topic([line])["last"], "block prompt")

    def test_ignores_assistant_turns(self):
        lines = self._lines("mine") + [json.dumps({"type": "assistant", "message": {"content": "theirs"}})]
        self.assertEqual(ccwho.extract_topic(lines)["last"], "mine")

    def test_collapses_whitespace_and_newlines(self):
        self.assertEqual(ccwho.extract_topic(self._lines("a\n\n  b   c"))["last"], "a b c")

    def test_no_user_messages(self):
        got = ccwho.extract_topic([])
        self.assertEqual(got["last"], "")
        self.assertEqual(got["first"], "")

    def test_bad_lines_do_not_crash(self):
        self.assertEqual(ccwho.extract_topic(["{bad", ""] + self._lines("ok"))["last"], "ok")


class TestBoilerplate(unittest.TestCase):
    def _lines(self, *msgs):
        return [json.dumps({"type": "user", "message": {"content": m}}) for m in msgs]

    def test_skill_preamble_is_not_a_topic(self):
        got = ccwho.extract_topic(self._lines(
            "fix the flaky test",
            "Base directory for this skill: /Users/x/.claude/skills/review",
        ))
        self.assertEqual(got["last"], "fix the flaky test")

    def test_compaction_notice_is_not_a_topic(self):
        got = ccwho.extract_topic(self._lines(
            "port the metrics row",
            "This session is being continued from a previous conversation that ran out of context",
        ))
        self.assertEqual(got["last"], "port the metrics row")

    def test_local_command_caveat_is_not_a_topic(self):
        got = ccwho.extract_topic(self._lines(
            "land it",
            "Caveat: The messages below were generated by the user while running local commands",
        ))
        self.assertEqual(got["last"], "land it")

    def test_all_boilerplate_falls_back_to_boilerplate_not_empty(self):
        got = ccwho.extract_topic(self._lines("Base directory for this skill: /x"))
        self.assertTrue(got["last"].startswith("Base directory"))

    def test_strict_mode_returns_empty_rather_than_boilerplate(self):
        got = ccwho.extract_topic(self._lines("<task-notification>x</>"), strict=True)
        self.assertEqual(got["last"], "")

    def test_strict_mode_still_returns_real_prompts(self):
        got = ccwho.extract_topic(self._lines("real one", "<task-notification>x</>"), strict=True)
        self.assertEqual(got["last"], "real one")

    def test_nonstrict_still_falls_back(self):
        got = ccwho.extract_topic(self._lines("Base directory for this skill: /x"), strict=False)
        self.assertTrue(got["last"].startswith("Base directory"))

    def test_is_boilerplate_predicate(self):
        self.assertTrue(ccwho.is_boilerplate("Base directory for this skill: /x"))
        self.assertFalse(ccwho.is_boilerplate("run the gate"))


class TestTitle(unittest.TestCase):
    def test_reads_ai_title(self):
        lines = [json.dumps({"type": "ai-title", "aiTitle": "PR review workflow redesign"})]
        self.assertEqual(ccwho.extract_title(lines), "PR review workflow redesign")

    def test_last_ai_title_wins(self):
        lines = [json.dumps({"type": "ai-title", "aiTitle": "old"}),
                 json.dumps({"type": "ai-title", "aiTitle": "new"})]
        self.assertEqual(ccwho.extract_title(lines), "new")

    def test_no_title_is_empty(self):
        self.assertEqual(ccwho.extract_title([json.dumps({"type": "user"})]), "")

    def test_bad_lines_do_not_crash(self):
        self.assertEqual(ccwho.extract_title(["{oops"]), "")


class TestDoing(unittest.TestCase):
    def _tool(self, name, **inp):
        return json.dumps({"type": "assistant", "message": {"content": [
            {"type": "tool_use", "name": name, "input": inp}]}})

    def test_prefers_bash_description_over_raw_command(self):
        got = ccwho.extract_doing([self._tool("Bash", command="rm -rf /x", description="Record evidence")])
        self.assertEqual(got, "Bash: Record evidence")

    def test_falls_back_to_command_when_no_description(self):
        got = ccwho.extract_doing([self._tool("Bash", command="pytest -x")])
        self.assertEqual(got, "Bash: pytest -x")

    def test_file_tools_show_the_file(self):
        got = ccwho.extract_doing([self._tool("Edit", file_path="/a/b/ccwho.py")])
        self.assertEqual(got, "Edit: ccwho.py")

    def test_last_tool_wins(self):
        got = ccwho.extract_doing([self._tool("Read", file_path="/a.py"), self._tool("Grep", pattern="foo")])
        self.assertTrue(got.startswith("Grep"))

    def test_collapses_multiline_commands(self):
        got = ccwho.extract_doing([self._tool("Bash", command="line one\nline two")])
        self.assertEqual(got, "Bash: line one line two")

    def test_no_tools_is_empty(self):
        self.assertEqual(ccwho.extract_doing([]), "")


class TestSince(unittest.TestCase):
    def test_seconds_then_minutes(self):
        self.assertEqual(ccwho.since(100.0, now=105.0), "5s")
        self.assertEqual(ccwho.since(0.0, now=300.0), "5m")

    def test_hours_and_days(self):
        self.assertEqual(ccwho.since(0.0, now=7200.0), "2h")
        self.assertEqual(ccwho.since(0.0, now=172800.0), "2d")

    def test_missing_is_question_mark(self):
        self.assertEqual(ccwho.since(None, now=1.0), "?")


class TestOrphans(unittest.TestCase):
    PS = "\n".join([
        "  PID  PPID COMMAND",
        " 1000     1 bash -c scripts/check.sh > /tmp/claude-501/proj/aaa/scratchpad/g.log",
        " 1001     1 node /some/other/thing.ts",
        " 1002   999 bash -c owned-by-a-live-parent /tmp/.../aaa/...",
    ])

    def test_attributes_orphan_to_session_by_id_in_cmdline(self):
        got = ccwho.attribute_orphans(self.PS, ["aaa", "bbb"])
        self.assertEqual(got["aaa"], 1)
        self.assertEqual(got.get("bbb", 0), 0)

    def test_ignores_processes_with_a_live_parent(self):
        # pid 1002 mentions aaa but ppid is 999, so it is not detached
        self.assertEqual(ccwho.attribute_orphans(self.PS, ["aaa"])["aaa"], 1)

    def test_counts_unattributed_orphans_separately(self):
        self.assertEqual(ccwho.count_orphans(self.PS), 2)

    def test_home_filter_excludes_system_daemons(self):
        ps = "\n".join([
            "  PID  PPID COMMAND",
            " 100     1 /usr/libexec/diagnosticd",
            " 101     1 /System/Library/whatever",
            " 102     1 node /Users/me/projects/app/thing.ts",
        ])
        self.assertEqual(ccwho.count_orphans(ps), 3)
        self.assertEqual(ccwho.count_orphans(ps, home="/Users/me"), 1)

    def test_empty_ps_output(self):
        self.assertEqual(ccwho.count_orphans(""), 0)
        self.assertEqual(ccwho.attribute_orphans("", ["aaa"]), {"aaa": 0})


class TestSorting(unittest.TestCase):
    def test_needs_you_sorts_first(self):
        rows = [
            {"status": "idle", "project": "a", "name": "i"},
            {"status": "waiting", "project": "z", "name": "w"},
            {"status": "busy", "project": "a", "name": "b"},
        ]
        got = [r["name"] for r in sorted(rows, key=ccwho.sort_key)]
        self.assertEqual(got[0], "w")

    def test_busy_before_idle(self):
        rows = [{"status": "idle", "project": "a", "name": "i"},
                {"status": "busy", "project": "a", "name": "b"}]
        got = [r["name"] for r in sorted(rows, key=ccwho.sort_key)]
        self.assertEqual(got, ["b", "i"])

    def test_unknown_status_does_not_crash(self):
        rows = [{"status": "weird", "project": "a", "name": "x"}]
        self.assertEqual(sorted(rows, key=ccwho.sort_key)[0]["name"], "x")


class TestAge(unittest.TestCase):
    def test_formats_minutes_hours_days(self):
        self.assertEqual(ccwho.age(1000 * 1000, now=1000 * 1000 + 5 * 60_000), "5m")
        self.assertEqual(ccwho.age(0, now=3 * 3600_000), "3h")
        self.assertEqual(ccwho.age(0, now=2 * 86400_000), "2d")

    def test_missing_timestamp(self):
        self.assertEqual(ccwho.age(None, now=1000), "?")


class TestTruncate(unittest.TestCase):
    def test_truncates_with_ellipsis(self):
        self.assertEqual(ccwho.truncate("abcdefghij", 5), "abcd…")

    def test_short_string_untouched(self):
        self.assertEqual(ccwho.truncate("abc", 5), "abc")


if __name__ == "__main__":
    unittest.main()


class TestGateLine(unittest.TestCase):
    def setUp(self):
        import tempfile
        self.dir = tempfile.mkdtemp()

    def test_empty_when_no_slots_held(self):
        self.assertEqual(ccwho.gate_line(self.dir), "")

    def test_names_holders_and_count(self):
        import ccgate
        ccgate.claim_slot(self.dir, 2, pid=os.getpid(), label="liveapp gate")
        got = ccwho.gate_line(self.dir)
        self.assertIn("1 gate", got)
        self.assertIn("liveapp gate", got)

    def test_missing_dir_is_not_an_error(self):
        self.assertEqual(ccwho.gate_line("/nonexistent/path/xyz"), "")


class TestWaitingKind(unittest.TestCase):
    """A session Claude Code calls `waiting` may be blocked on a prompt, or may
    simply have finished its turn. Only the first deserves NEEDS YOU."""

    def _assistant(self, stop_reason, tool_id=None):
        content = [{"type": "text", "text": "hi"}]
        if tool_id:
            content = [{"type": "tool_use", "id": tool_id, "name": "Bash", "input": {}}]
        return json.dumps({"type": "assistant",
                           "message": {"stop_reason": stop_reason, "content": content}})

    def _result(self, tool_id):
        return json.dumps({"type": "user", "message": {"content": [
            {"type": "tool_result", "tool_use_id": tool_id, "content": "ok"}]}})

    def test_end_turn_with_nothing_pending_is_ready(self):
        self.assertEqual(ccwho.waiting_kind([self._assistant("end_turn")]), "ready")

    def test_unanswered_tool_use_is_blocked(self):
        lines = [self._assistant("tool_use", tool_id="t1")]
        self.assertEqual(ccwho.waiting_kind(lines), "blocked")

    def test_answered_tool_use_is_ready(self):
        lines = [self._assistant("tool_use", tool_id="t1"), self._result("t1")]
        self.assertEqual(ccwho.waiting_kind(lines), "ready")

    def test_one_of_two_answered_is_still_blocked(self):
        lines = [self._assistant("tool_use", tool_id="t1"),
                 self._assistant("tool_use", tool_id="t2"), self._result("t1")]
        self.assertEqual(ccwho.waiting_kind(lines), "blocked")

    def test_empty_transcript_is_ready_not_blocked(self):
        self.assertEqual(ccwho.waiting_kind([]), "ready")

    def test_bad_lines_do_not_crash(self):
        self.assertEqual(ccwho.waiting_kind(["{bad"]), "ready")


class TestAttentionSort(unittest.TestCase):
    def test_blocked_outranks_busy(self):
        rows = [{"attention": "busy", "status": "busy", "project": "a", "name": "b"},
                {"attention": "blocked", "status": "waiting", "project": "z", "name": "w"}]
        self.assertEqual(sorted(rows, key=ccwho.sort_key)[0]["name"], "w")

    def test_ready_sorts_below_busy(self):
        rows = [{"attention": "ready", "status": "waiting", "project": "a", "name": "r"},
                {"attention": "busy", "status": "busy", "project": "a", "name": "b"}]
        self.assertEqual([r["name"] for r in sorted(rows, key=ccwho.sort_key)], ["b", "r"])

    def test_ready_sorts_above_idle(self):
        rows = [{"attention": "idle", "status": "idle", "project": "a", "name": "i"},
                {"attention": "ready", "status": "waiting", "project": "a", "name": "r"}]
        self.assertEqual([r["name"] for r in sorted(rows, key=ccwho.sort_key)], ["r", "i"])

    def test_falls_back_to_status_when_attention_absent(self):
        rows = [{"status": "idle", "project": "a", "name": "i"},
                {"status": "busy", "project": "a", "name": "b"}]
        self.assertEqual([r["name"] for r in sorted(rows, key=ccwho.sort_key)], ["b", "i"])


class TestAsksUser(unittest.TestCase):
    """The harness reports `idle` for a session that ended its turn with a
    question. Whether it needs you is in the closing line, not the status field."""

    def test_closing_question_mark(self):
        self.assertTrue(ccwho.asks_user("Did the work.\n\nWant me to build S2a?"))

    def test_markdown_is_stripped_before_matching(self):
        self.assertTrue(ccwho.asks_user("**Want me to build S2a?**"))

    def test_imperative_request_without_a_question_mark(self):
        self.assertTrue(ccwho.asks_user("Tell me which and I'll finish it and land."))

    def test_say_the_word(self):
        self.assertTrue(ccwho.asks_user("Outside this change's scope - say the word and it's a one-liner."))

    def test_your_call(self):
        self.assertTrue(ccwho.asks_user("It's your machine and your call; I'm not killing anything."))

    def test_plain_statement_is_not_an_ask(self):
        self.assertFalse(ccwho.asks_user("Idle and ready."))

    def test_report_of_results_is_not_an_ask(self):
        self.assertFalse(ccwho.asks_user("234 tests green, typecheck clean."))

    def test_the_word_question_alone_is_not_an_ask(self):
        self.assertFalse(ccwho.asks_user("Still open, not blocking: the spend labelling question."))

    def test_only_the_closing_line_counts(self):
        self.assertFalse(ccwho.asks_user("Should I do X?\n\nDone, all landed."))

    def test_empty_text(self):
        self.assertFalse(ccwho.asks_user(""))


class TestExtractAsk(unittest.TestCase):
    def _msg(self, text):
        return json.dumps({"type": "assistant", "message": {"content": [
            {"type": "text", "text": text}]}})

    def test_returns_the_closing_line(self):
        got = ccwho.extract_ask([self._msg("Did work.\n\nWant me to build S2a?")])
        self.assertEqual(got, "Want me to build S2a?")

    def test_empty_when_not_asking(self):
        self.assertEqual(ccwho.extract_ask([self._msg("All done.")]), "")

    def test_uses_the_last_assistant_message(self):
        lines = [self._msg("Want me to do X?"), self._msg("Never mind, finished.")]
        self.assertEqual(ccwho.extract_ask(lines), "")

    def test_no_messages(self):
        self.assertEqual(ccwho.extract_ask([]), "")


class TestAsksRanking(unittest.TestCase):
    def test_asks_outranks_busy(self):
        rows = [{"attention": "busy", "project": "a", "name": "b"},
                {"attention": "asks", "project": "z", "name": "q"}]
        self.assertEqual(sorted(rows, key=ccwho.sort_key)[0]["name"], "q")

    def test_blocked_still_outranks_asks(self):
        rows = [{"attention": "asks", "project": "a", "name": "q"},
                {"attention": "blocked", "project": "z", "name": "x"}]
        self.assertEqual(sorted(rows, key=ccwho.sort_key)[0]["name"], "x")

    def test_asks_outranks_idle(self):
        rows = [{"attention": "idle", "project": "a", "name": "i"},
                {"attention": "asks", "project": "a", "name": "q"}]
        self.assertEqual([r["name"] for r in sorted(rows, key=ccwho.sort_key)], ["q", "i"])
