"""Tests for ccwho. Stdlib only: python3 -m unittest -v"""
import json
import unittest

import ccwho


class TestParseSessions(unittest.TestCase):
    def test_parses_agents_json(self):
        raw = json.dumps([
            {"pid": 1, "cwd": "/Users/x/projects/liveapp", "kind": "interactive",
             "startedAt": 1000, "sessionId": "aaa", "name": "liveapp-4e", "status": "busy"},
        ])
        got = ccwho.parse_sessions(raw)
        self.assertEqual(len(got), 1)
        self.assertEqual(got[0]["name"], "liveapp-4e")

    def test_empty_input_is_not_an_error(self):
        self.assertEqual(ccwho.parse_sessions("[]"), [])

    def test_malformed_json_returns_empty(self):
        self.assertEqual(ccwho.parse_sessions("not json"), [])


class TestProject(unittest.TestCase):
    def test_project_is_last_path_component(self):
        self.assertEqual(ccwho.project_of("/Users/x/projects/liveapp"), "liveapp")

    def test_worktree_keeps_parent_repo_name(self):
        cwd = "/Users/x/projects/football/.claude/worktrees/fix-nav"
        self.assertEqual(ccwho.project_of(cwd), "football")

    def test_missing_cwd(self):
        self.assertEqual(ccwho.project_of(""), "?")


class TestTopic(unittest.TestCase):
    def _lines(self, *msgs):
        out = []
        for m in msgs:
            out.append(json.dumps({"type": "user", "message": {"content": m}}))
        return out

    def test_last_user_prompt_is_the_topic(self):
        got = ccwho.extract_topic(self._lines("first thing", "second thing"))
        self.assertEqual(got["last"], "second thing")
        self.assertEqual(got["first"], "first thing")

    def test_skips_system_reminders_and_tool_noise(self):
        got = ccwho.extract_topic(self._lines("real prompt", "<system-reminder>noise</>"))
        self.assertEqual(got["last"], "real prompt")

    def test_handles_content_as_block_list(self):
        line = json.dumps({"type": "user", "message": {"content": [
            {"type": "text", "text": "block prompt"},
            {"type": "tool_result", "content": "ignored"},
        ]}})
        self.assertEqual(ccwho.extract_topic([line])["last"], "block prompt")

    def test_ignores_assistant_turns(self):
        lines = self._lines("mine") + [json.dumps({"type": "assistant", "message": {"content": "theirs"}})]
        self.assertEqual(ccwho.extract_topic(lines)["last"], "mine")

    def test_collapses_whitespace_and_newlines(self):
        self.assertEqual(ccwho.extract_topic(self._lines("a\n\n  b   c"))["last"], "a b c")

    def test_no_user_messages(self):
        got = ccwho.extract_topic([])
        self.assertEqual(got["last"], "")
        self.assertEqual(got["first"], "")

    def test_bad_lines_do_not_crash(self):
        self.assertEqual(ccwho.extract_topic(["{bad", ""] + self._lines("ok"))["last"], "ok")


class TestBoilerplate(unittest.TestCase):
    def _lines(self, *msgs):
        return [json.dumps({"type": "user", "message": {"content": m}}) for m in msgs]

    def test_skill_preamble_is_not_a_topic(self):
        got = ccwho.extract_topic(self._lines(
            "fix the flaky test",
            "Base directory for this skill: /Users/x/.claude/skills/review",
        ))
        self.assertEqual(got["last"], "fix the flaky test")

    def test_compaction_notice_is_not_a_topic(self):
        got = ccwho.extract_topic(self._lines(
            "port the metrics row",
            "This session is being continued from a previous conversation that ran out of context",
        ))
        self.assertEqual(got["last"], "port the metrics row")

    def test_local_command_caveat_is_not_a_topic(self):
        got = ccwho.extract_topic(self._lines(
            "land it",
            "Caveat: The messages below were generated by the user while running local commands",
        ))
        self.assertEqual(got["last"], "land it")

    def test_all_boilerplate_falls_back_to_boilerplate_not_empty(self):
        got = ccwho.extract_topic(self._lines("Base directory for this skill: /x"))
        self.assertTrue(got["last"].startswith("Base directory"))

    def test_strict_mode_returns_empty_rather_than_boilerplate(self):
        got = ccwho.extract_topic(self._lines("<task-notification>x</>"), strict=True)
        self.assertEqual(got["last"], "")

    def test_strict_mode_still_returns_real_prompts(self):
        got = ccwho.extract_topic(self._lines("real one", "<task-notification>x</>"), strict=True)
        self.assertEqual(got["last"], "real one")

    def test_nonstrict_still_falls_back(self):
        got = ccwho.extract_topic(self._lines("Base directory for this skill: /x"), strict=False)
        self.assertTrue(got["last"].startswith("Base directory"))

    def test_is_boilerplate_predicate(self):
        self.assertTrue(ccwho.is_boilerplate("Base directory for this skill: /x"))
        self.assertFalse(ccwho.is_boilerplate("run the gate"))


class TestOrphans(unittest.TestCase):
    PS = "\n".join([
        "  PID  PPID COMMAND",
        " 1000     1 bash -c scripts/check.sh > /tmp/claude-501/proj/aaa/scratchpad/g.log",
        " 1001     1 node /some/other/thing.ts",
        " 1002   999 bash -c owned-by-a-live-parent /tmp/.../aaa/...",
    ])

    def test_attributes_orphan_to_session_by_id_in_cmdline(self):
        got = ccwho.attribute_orphans(self.PS, ["aaa", "bbb"])
        self.assertEqual(got["aaa"], 1)
        self.assertEqual(got.get("bbb", 0), 0)

    def test_ignores_processes_with_a_live_parent(self):
        # pid 1002 mentions aaa but ppid is 999, so it is not detached
        self.assertEqual(ccwho.attribute_orphans(self.PS, ["aaa"])["aaa"], 1)

    def test_counts_unattributed_orphans_separately(self):
        self.assertEqual(ccwho.count_orphans(self.PS), 2)

    def test_home_filter_excludes_system_daemons(self):
        ps = "\n".join([
            "  PID  PPID COMMAND",
            " 100     1 /usr/libexec/diagnosticd",
            " 101     1 /System/Library/whatever",
            " 102     1 node /Users/me/projects/app/thing.ts",
        ])
        self.assertEqual(ccwho.count_orphans(ps), 3)
        self.assertEqual(ccwho.count_orphans(ps, home="/Users/me"), 1)

    def test_empty_ps_output(self):
        self.assertEqual(ccwho.count_orphans(""), 0)
        self.assertEqual(ccwho.attribute_orphans("", ["aaa"]), {"aaa": 0})


class TestSorting(unittest.TestCase):
    def test_needs_you_sorts_first(self):
        rows = [
            {"status": "idle", "project": "a", "name": "i"},
            {"status": "waiting", "project": "z", "name": "w"},
            {"status": "busy", "project": "a", "name": "b"},
        ]
        got = [r["name"] for r in sorted(rows, key=ccwho.sort_key)]
        self.assertEqual(got[0], "w")

    def test_busy_before_idle(self):
        rows = [{"status": "idle", "project": "a", "name": "i"},
                {"status": "busy", "project": "a", "name": "b"}]
        got = [r["name"] for r in sorted(rows, key=ccwho.sort_key)]
        self.assertEqual(got, ["b", "i"])

    def test_unknown_status_does_not_crash(self):
        rows = [{"status": "weird", "project": "a", "name": "x"}]
        self.assertEqual(sorted(rows, key=ccwho.sort_key)[0]["name"], "x")


class TestAge(unittest.TestCase):
    def test_formats_minutes_hours_days(self):
        self.assertEqual(ccwho.age(1000 * 1000, now=1000 * 1000 + 5 * 60_000), "5m")
        self.assertEqual(ccwho.age(0, now=3 * 3600_000), "3h")
        self.assertEqual(ccwho.age(0, now=2 * 86400_000), "2d")

    def test_missing_timestamp(self):
        self.assertEqual(ccwho.age(None, now=1000), "?")


class TestTruncate(unittest.TestCase):
    def test_truncates_with_ellipsis(self):
        self.assertEqual(ccwho.truncate("abcdefghij", 5), "abcd…")

    def test_short_string_untouched(self):
        self.assertEqual(ccwho.truncate("abc", 5), "abc")


if __name__ == "__main__":
    unittest.main()
