"""Tests for ccwho. Stdlib only: python3 -m unittest -v"""
import json
import os
import unittest

import ccwho_engine as ccwho


class TestParseSessions(unittest.TestCase):
    def test_parses_agents_json(self):
        raw = json.dumps([
            {"pid": 1, "cwd": "/Users/x/projects/liveapp", "kind": "interactive",
             "startedAt": 1000, "sessionId": "aaa", "name": "liveapp-4e", "status": "busy"},
        ])
        got = ccwho.parse_sessions(raw)
        self.assertEqual(len(got), 1)
        self.assertEqual(got[0]["name"], "liveapp-4e")

    def test_empty_input_is_not_an_error(self):
        self.assertEqual(ccwho.parse_sessions("[]"), [])

    def test_malformed_json_returns_empty(self):
        self.assertEqual(ccwho.parse_sessions("not json"), [])


class TestProject(unittest.TestCase):
    def test_project_is_last_path_component(self):
        self.assertEqual(ccwho.project_of("/Users/x/projects/liveapp"), "liveapp")

    def test_worktree_keeps_parent_repo_name(self):
        cwd = "/Users/x/projects/football/.claude/worktrees/fix-nav"
        self.assertEqual(ccwho.project_of(cwd), "football")

    def test_missing_cwd(self):
        self.assertEqual(ccwho.project_of(""), "?")


class TestTopic(unittest.TestCase):
    def _lines(self, *msgs):
        out = []
        for m in msgs:
            out.append(json.dumps({"type": "user", "message": {"content": m}}))
        return out

    def test_last_user_prompt_is_the_topic(self):
        got = ccwho.extract_topic(self._lines("first thing", "second thing"))
        self.assertEqual(got["last"], "second thing")
        self.assertEqual(got["first"], "first thing")

    def test_skips_system_reminders_and_tool_noise(self):
        got = ccwho.extract_topic(self._lines("real prompt", "<system-reminder>noise</>"))
        self.assertEqual(got["last"], "real prompt")

    def test_handles_content_as_block_list(self):
        line = json.dumps({"type": "user", "message": {"content": [
            {"type": "text", "text": "block prompt"},
            {"type": "tool_result", "content": "ignored"},
        ]}})
        self.assertEqual(ccwho.extract_topic([line])["last"], "block prompt")

    def test_ignores_assistant_turns(self):
        lines = self._lines("mine") + [json.dumps({"type": "assistant", "message": {"content": "theirs"}})]
        self.assertEqual(ccwho.extract_topic(lines)["last"], "mine")

    def test_collapses_whitespace_and_newlines(self):
        self.assertEqual(ccwho.extract_topic(self._lines("a\n\n  b   c"))["last"], "a b c")

    def test_no_user_messages(self):
        got = ccwho.extract_topic([])
        self.assertEqual(got["last"], "")
        self.assertEqual(got["first"], "")

    def test_bad_lines_do_not_crash(self):
        self.assertEqual(ccwho.extract_topic(["{bad", ""] + self._lines("ok"))["last"], "ok")


class TestBoilerplate(unittest.TestCase):
    def _lines(self, *msgs):
        return [json.dumps({"type": "user", "message": {"content": m}}) for m in msgs]

    def test_skill_preamble_is_not_a_topic(self):
        got = ccwho.extract_topic(self._lines(
            "fix the flaky test",
            "Base directory for this skill: /Users/x/.claude/skills/review",
        ))
        self.assertEqual(got["last"], "fix the flaky test")

    def test_compaction_notice_is_not_a_topic(self):
        got = ccwho.extract_topic(self._lines(
            "port the metrics row",
            "This session is being continued from a previous conversation that ran out of context",
        ))
        self.assertEqual(got["last"], "port the metrics row")

    def test_local_command_caveat_is_not_a_topic(self):
        got = ccwho.extract_topic(self._lines(
            "land it",
            "Caveat: The messages below were generated by the user while running local commands",
        ))
        self.assertEqual(got["last"], "land it")

    def test_all_boilerplate_falls_back_to_boilerplate_not_empty(self):
        got = ccwho.extract_topic(self._lines("Base directory for this skill: /x"))
        self.assertTrue(got["last"].startswith("Base directory"))

    def test_strict_mode_returns_empty_rather_than_boilerplate(self):
        got = ccwho.extract_topic(self._lines("<task-notification>x</>"), strict=True)
        self.assertEqual(got["last"], "")

    def test_strict_mode_still_returns_real_prompts(self):
        got = ccwho.extract_topic(self._lines("real one", "<task-notification>x</>"), strict=True)
        self.assertEqual(got["last"], "real one")

    def test_nonstrict_still_falls_back(self):
        got = ccwho.extract_topic(self._lines("Base directory for this skill: /x"), strict=False)
        self.assertTrue(got["last"].startswith("Base directory"))

    def test_is_boilerplate_predicate(self):
        self.assertTrue(ccwho.is_boilerplate("Base directory for this skill: /x"))
        self.assertFalse(ccwho.is_boilerplate("run the gate"))


class TestTitle(unittest.TestCase):
    def test_reads_ai_title(self):
        lines = [json.dumps({"type": "ai-title", "aiTitle": "PR review workflow redesign"})]
        self.assertEqual(ccwho.extract_title(lines), "PR review workflow redesign")

    def test_last_ai_title_wins(self):
        lines = [json.dumps({"type": "ai-title", "aiTitle": "old"}),
                 json.dumps({"type": "ai-title", "aiTitle": "new"})]
        self.assertEqual(ccwho.extract_title(lines), "new")

    def test_no_title_is_empty(self):
        self.assertEqual(ccwho.extract_title([json.dumps({"type": "user"})]), "")

    def test_bad_lines_do_not_crash(self):
        self.assertEqual(ccwho.extract_title(["{oops"]), "")


class TestDoing(unittest.TestCase):
    def _tool(self, name, **inp):
        return json.dumps({"type": "assistant", "message": {"content": [
            {"type": "tool_use", "name": name, "input": inp}]}})

    def test_prefers_bash_description_over_raw_command(self):
        got = ccwho.extract_doing([self._tool("Bash", command="rm -rf /x", description="Record evidence")])
        self.assertEqual(got, "Bash: Record evidence")

    def test_falls_back_to_command_when_no_description(self):
        got = ccwho.extract_doing([self._tool("Bash", command="pytest -x")])
        self.assertEqual(got, "Bash: pytest -x")

    def test_file_tools_show_the_file(self):
        got = ccwho.extract_doing([self._tool("Edit", file_path="/a/b/ccwho.py")])
        self.assertEqual(got, "Edit: ccwho.py")

    def test_last_tool_wins(self):
        got = ccwho.extract_doing([self._tool("Read", file_path="/a.py"), self._tool("Grep", pattern="foo")])
        self.assertTrue(got.startswith("Grep"))

    def test_collapses_multiline_commands(self):
        got = ccwho.extract_doing([self._tool("Bash", command="line one\nline two")])
        self.assertEqual(got, "Bash: line one line two")

    def test_no_tools_is_empty(self):
        self.assertEqual(ccwho.extract_doing([]), "")


class TestSince(unittest.TestCase):
    def test_seconds_then_minutes(self):
        self.assertEqual(ccwho.since(100.0, now=105.0), "5s")
        self.assertEqual(ccwho.since(0.0, now=300.0), "5m")

    def test_hours_and_days(self):
        self.assertEqual(ccwho.since(0.0, now=7200.0), "2h")
        self.assertEqual(ccwho.since(0.0, now=172800.0), "2d")

    def test_missing_is_question_mark(self):
        self.assertEqual(ccwho.since(None, now=1.0), "?")


class TestOrphans(unittest.TestCase):
    PS = "\n".join([
        "  PID  PPID COMMAND",
        " 1000     1 bash -c scripts/check.sh > /tmp/claude-501/proj/aaa/scratchpad/g.log",
        " 1001     1 node /some/other/thing.ts",
        " 1002   999 bash -c owned-by-a-live-parent /tmp/.../aaa/...",
    ])

    def test_attributes_orphan_to_session_by_id_in_cmdline(self):
        got = ccwho.attribute_orphans(self.PS, ["aaa", "bbb"])
        self.assertEqual(got["aaa"], 1)
        self.assertEqual(got.get("bbb", 0), 0)

    def test_ignores_processes_with_a_live_parent(self):
        # pid 1002 mentions aaa but ppid is 999, so it is not detached
        self.assertEqual(ccwho.attribute_orphans(self.PS, ["aaa"])["aaa"], 1)

    def test_counts_unattributed_orphans_separately(self):
        self.assertEqual(ccwho.count_orphans(self.PS), 2)

    def test_home_filter_excludes_system_daemons(self):
        ps = "\n".join([
            "  PID  PPID COMMAND",
            " 100     1 /usr/libexec/diagnosticd",
            " 101     1 /System/Library/whatever",
            " 102     1 node /Users/me/projects/app/thing.ts",
        ])
        self.assertEqual(ccwho.count_orphans(ps), 3)
        self.assertEqual(ccwho.count_orphans(ps, home="/Users/me"), 1)

    def test_empty_ps_output(self):
        self.assertEqual(ccwho.count_orphans(""), 0)
        self.assertEqual(ccwho.attribute_orphans("", ["aaa"]), {"aaa": 0})


class TestSorting(unittest.TestCase):
    def test_needs_you_sorts_first(self):
        rows = [
            {"status": "idle", "project": "a", "name": "i"},
            {"status": "waiting", "project": "z", "name": "w"},
            {"status": "busy", "project": "a", "name": "b"},
        ]
        got = [r["name"] for r in sorted(rows, key=ccwho.sort_key)]
        self.assertEqual(got[0], "w")

    def test_busy_before_idle(self):
        rows = [{"status": "idle", "project": "a", "name": "i"},
                {"status": "busy", "project": "a", "name": "b"}]
        got = [r["name"] for r in sorted(rows, key=ccwho.sort_key)]
        self.assertEqual(got, ["b", "i"])

    def test_unknown_status_does_not_crash(self):
        rows = [{"status": "weird", "project": "a", "name": "x"}]
        self.assertEqual(sorted(rows, key=ccwho.sort_key)[0]["name"], "x")


class TestAge(unittest.TestCase):
    def test_formats_minutes_hours_days(self):
        self.assertEqual(ccwho.age(1000 * 1000, now=1000 * 1000 + 5 * 60_000), "5m")
        self.assertEqual(ccwho.age(0, now=3 * 3600_000), "3h")
        self.assertEqual(ccwho.age(0, now=2 * 86400_000), "2d")

    def test_missing_timestamp(self):
        self.assertEqual(ccwho.age(None, now=1000), "?")


class TestTruncate(unittest.TestCase):
    def test_truncates_with_ellipsis(self):
        self.assertEqual(ccwho.truncate("abcdefghij", 5), "abcd…")

    def test_short_string_untouched(self):
        self.assertEqual(ccwho.truncate("abc", 5), "abc")


if __name__ == "__main__":
    unittest.main()


class TestGateLine(unittest.TestCase):
    def setUp(self):
        import tempfile
        self.dir = tempfile.mkdtemp()

    def test_empty_when_no_slots_held(self):
        self.assertEqual(ccwho.gate_line(self.dir), "")

    def test_names_holders_and_count(self):
        import ccgate
        ccgate.claim_slot(self.dir, 2, pid=os.getpid(), label="liveapp gate")
        got = ccwho.gate_line(self.dir)
        self.assertIn("1 gate", got)
        self.assertIn("liveapp gate", got)

    def test_missing_dir_is_not_an_error(self):
        self.assertEqual(ccwho.gate_line("/nonexistent/path/xyz"), "")


class TestWaitingKind(unittest.TestCase):
    """A session Claude Code calls `waiting` may be blocked on a prompt, or may
    simply have finished its turn. Only the first deserves NEEDS YOU."""

    def _assistant(self, stop_reason, tool_id=None):
        content = [{"type": "text", "text": "hi"}]
        if tool_id:
            content = [{"type": "tool_use", "id": tool_id, "name": "Bash", "input": {}}]
        return json.dumps({"type": "assistant",
                           "message": {"stop_reason": stop_reason, "content": content}})

    def _result(self, tool_id):
        return json.dumps({"type": "user", "message": {"content": [
            {"type": "tool_result", "tool_use_id": tool_id, "content": "ok"}]}})

    def test_end_turn_with_nothing_pending_is_ready(self):
        self.assertEqual(ccwho.waiting_kind([self._assistant("end_turn")]), "ready")

    def test_unanswered_tool_use_is_blocked(self):
        lines = [self._assistant("tool_use", tool_id="t1")]
        self.assertEqual(ccwho.waiting_kind(lines), "blocked")

    def test_answered_tool_use_is_ready(self):
        lines = [self._assistant("tool_use", tool_id="t1"), self._result("t1")]
        self.assertEqual(ccwho.waiting_kind(lines), "ready")

    def test_one_of_two_answered_is_still_blocked(self):
        lines = [self._assistant("tool_use", tool_id="t1"),
                 self._assistant("tool_use", tool_id="t2"), self._result("t1")]
        self.assertEqual(ccwho.waiting_kind(lines), "blocked")

    def test_empty_transcript_is_ready_not_blocked(self):
        self.assertEqual(ccwho.waiting_kind([]), "ready")

    def test_bad_lines_do_not_crash(self):
        self.assertEqual(ccwho.waiting_kind(["{bad"]), "ready")


class TestAttentionSort(unittest.TestCase):
    def test_blocked_outranks_busy(self):
        rows = [{"attention": "busy", "status": "busy", "project": "a", "name": "b"},
                {"attention": "blocked", "status": "waiting", "project": "z", "name": "w"}]
        self.assertEqual(sorted(rows, key=ccwho.sort_key)[0]["name"], "w")

    def test_ready_sorts_below_busy(self):
        rows = [{"attention": "ready", "status": "waiting", "project": "a", "name": "r"},
                {"attention": "busy", "status": "busy", "project": "a", "name": "b"}]
        self.assertEqual([r["name"] for r in sorted(rows, key=ccwho.sort_key)], ["b", "r"])

    def test_ready_sorts_above_idle(self):
        rows = [{"attention": "idle", "status": "idle", "project": "a", "name": "i"},
                {"attention": "ready", "status": "waiting", "project": "a", "name": "r"}]
        self.assertEqual([r["name"] for r in sorted(rows, key=ccwho.sort_key)], ["r", "i"])

    def test_falls_back_to_status_when_attention_absent(self):
        rows = [{"status": "idle", "project": "a", "name": "i"},
                {"status": "busy", "project": "a", "name": "b"}]
        self.assertEqual([r["name"] for r in sorted(rows, key=ccwho.sort_key)], ["b", "i"])


class TestAsksUser(unittest.TestCase):
    """The harness reports `idle` for a session that ended its turn with a
    question. Whether it needs you is in the closing line, not the status field."""

    def test_closing_question_mark(self):
        self.assertTrue(ccwho.asks_user("Did the work.\n\nWant me to build S2a?"))

    def test_markdown_is_stripped_before_matching(self):
        self.assertTrue(ccwho.asks_user("**Want me to build S2a?**"))

    def test_imperative_request_without_a_question_mark(self):
        self.assertTrue(ccwho.asks_user("Tell me which and I'll finish it and land."))

    def test_say_the_word(self):
        self.assertTrue(ccwho.asks_user("Outside this change's scope - say the word and it's a one-liner."))

    def test_your_call(self):
        self.assertTrue(ccwho.asks_user("It's your machine and your call; I'm not killing anything."))

    def test_plain_statement_is_not_an_ask(self):
        self.assertFalse(ccwho.asks_user("Idle and ready."))

    def test_report_of_results_is_not_an_ask(self):
        self.assertFalse(ccwho.asks_user("234 tests green, typecheck clean."))

    def test_the_word_question_alone_is_not_an_ask(self):
        self.assertFalse(ccwho.asks_user("Still open, not blocking: the spend labelling question."))

    def test_only_the_closing_line_counts(self):
        self.assertFalse(ccwho.asks_user("Should I do X?\n\nDone, all landed."))

    def test_empty_text(self):
        self.assertFalse(ccwho.asks_user(""))


class TestExtractAsk(unittest.TestCase):
    def _msg(self, text):
        return json.dumps({"type": "assistant", "message": {"content": [
            {"type": "text", "text": text}]}})

    def test_returns_the_closing_line(self):
        got = ccwho.extract_ask([self._msg("Did work.\n\nWant me to build S2a?")])
        self.assertEqual(got, "Want me to build S2a?")

    def test_empty_when_not_asking(self):
        self.assertEqual(ccwho.extract_ask([self._msg("All done.")]), "")

    def test_uses_the_last_assistant_message(self):
        lines = [self._msg("Want me to do X?"), self._msg("Never mind, finished.")]
        self.assertEqual(ccwho.extract_ask(lines), "")

    def test_no_messages(self):
        self.assertEqual(ccwho.extract_ask([]), "")


class TestAsksRanking(unittest.TestCase):
    def test_asks_outranks_busy(self):
        rows = [{"attention": "busy", "project": "a", "name": "b"},
                {"attention": "asks", "project": "z", "name": "q"}]
        self.assertEqual(sorted(rows, key=ccwho.sort_key)[0]["name"], "q")

    def test_blocked_still_outranks_asks(self):
        rows = [{"attention": "asks", "project": "a", "name": "q"},
                {"attention": "blocked", "project": "z", "name": "x"}]
        self.assertEqual(sorted(rows, key=ccwho.sort_key)[0]["name"], "x")

    def test_asks_outranks_idle(self):
        rows = [{"attention": "idle", "project": "a", "name": "i"},
                {"attention": "asks", "project": "a", "name": "q"}]
        self.assertEqual([r["name"] for r in sorted(rows, key=ccwho.sort_key)], ["q", "i"])


class TestLastTurnTs(unittest.TestCase):
    """File mtime is not activity: idle transcripts get metadata writes every few
    minutes, so mtime reported 4m for a session last worked on six days ago."""

    def _entry(self, typ, ts):
        return json.dumps({"type": typ, "timestamp": ts,
                           "message": {"content": [{"type": "text", "text": "x"}]}})

    def test_parses_iso_z(self):
        got = ccwho.last_turn_ts([self._entry("assistant", "2026-08-31T12:00:00.000Z")])
        self.assertAlmostEqual(got, 1788177600.0, places=0)

    def test_last_turn_wins(self):
        lines = [self._entry("assistant", "2026-08-30T12:00:00.000Z"),
                 self._entry("user", "2026-08-31T12:00:00.000Z")]
        self.assertAlmostEqual(ccwho.last_turn_ts(lines), 1788177600.0, places=0)

    def test_ignores_metadata_entries(self):
        lines = [self._entry("assistant", "2026-08-30T12:00:00.000Z"),
                 json.dumps({"type": "atis-latch", "timestamp": "2026-08-31T12:00:00.000Z"}),
                 json.dumps({"type": "bridge-session", "timestamp": "2026-08-31T12:00:00.000Z"})]
        self.assertAlmostEqual(ccwho.last_turn_ts(lines), 1788091200.0, places=0)

    def test_none_when_no_timestamps(self):
        self.assertIsNone(ccwho.last_turn_ts([json.dumps({"type": "assistant"})]))

    def test_bad_timestamp_is_skipped(self):
        lines = [self._entry("assistant", "2026-08-30T12:00:00.000Z"),
                 self._entry("assistant", "not-a-date")]
        self.assertAlmostEqual(ccwho.last_turn_ts(lines), 1788091200.0, places=0)

    def test_empty(self):
        self.assertIsNone(ccwho.last_turn_ts([]))


class TestRecencySort(unittest.TestCase):
    def test_newer_ask_sorts_above_older(self):
        # names chosen so alphabetical order gives the WRONG answer
        rows = [{"attention": "asks", "ts": 100, "project": "a", "name": "aaa-old"},
                {"attention": "asks", "ts": 900, "project": "a", "name": "zzz-new"}]
        self.assertEqual([r["name"] for r in sorted(rows, key=ccwho.sort_key)],
                         ["zzz-new", "aaa-old"])

    def test_rank_still_beats_recency(self):
        rows = [{"attention": "asks", "ts": 100, "project": "a", "name": "ask"},
                {"attention": "idle", "ts": 900, "project": "a", "name": "idle"}]
        self.assertEqual([r["name"] for r in sorted(rows, key=ccwho.sort_key)], ["ask", "idle"])

    def test_missing_ts_sorts_last_within_rank(self):
        rows = [{"attention": "asks", "project": "a", "name": "aaa-nots"},
                {"attention": "asks", "ts": 900, "project": "a", "name": "zzz-has"}]
        self.assertEqual([r["name"] for r in sorted(rows, key=ccwho.sort_key)],
                         ["zzz-has", "aaa-nots"])


class TestBuildRow(unittest.TestCase):
    """Covers the wiring collect() used to hide: which clock `since` reads from."""

    SESSION = {"sessionId": "s1", "cwd": "/Users/x/projects/liveapp",
               "status": "idle", "name": "liveapp-4e", "startedAt": 1788000000000}

    def _turn(self, ts, text="all done."):
        return json.dumps({"type": "assistant", "timestamp": ts,
                           "message": {"content": [{"type": "text", "text": text}]}})

    def test_since_uses_the_last_turn_not_file_mtime(self):
        # transcript last touched 6 days ago; file mtime is 60s old from metadata writes
        old = 1788177600.0 - 6 * 86400
        row = ccwho.build_row(self.SESSION, [], [self._turn("2026-08-25T12:00:00.000Z")],
                              mtime=1788177600.0 - 60, now=1788177600.0)
        self.assertEqual(row["since"], "6d")
        self.assertAlmostEqual(row["ts"], old, places=0)

    def test_falls_back_to_mtime_when_no_timestamps(self):
        row = ccwho.build_row(self.SESSION, [], [json.dumps({"type": "assistant"})],
                              mtime=1788177600.0 - 300, now=1788177600.0)
        self.assertEqual(row["since"], "5m")

    def test_ask_promotes_an_idle_session(self):
        tail = [self._turn("2026-08-31T12:00:00.000Z", "Want me to build S2a?")]
        row = ccwho.build_row(self.SESSION, [], tail, mtime=0, now=1788177600.0)
        self.assertEqual(row["attention"], "asks")
        self.assertEqual(row["ask"], "Want me to build S2a?")

    def test_plain_finish_with_no_background_work_is_stopped(self):
        tail = [self._turn("2026-08-31T12:00:00.000Z", "234 tests green.")]
        row = ccwho.build_row(self.SESSION, [], tail, mtime=0, now=1788177600.0, work=0)
        self.assertEqual(row["attention"], "stopped")
        self.assertEqual(row["ask"], "")

    def test_busy_is_never_reclassified_as_asks(self):
        s = dict(self.SESSION, status="busy")
        tail = [self._turn("2026-08-31T12:00:00.000Z", "Want me to build S2a?")]
        self.assertEqual(ccwho.build_row(s, [], tail, mtime=0, now=1788177600.0)["attention"], "busy")

    def test_project_and_title_are_carried(self):
        tail = [json.dumps({"type": "ai-title", "aiTitle": "Gate red triage"})]
        row = ccwho.build_row(self.SESSION, [], tail, mtime=0, now=1788177600.0)
        self.assertEqual(row["project"], "liveapp")
        self.assertEqual(row["title"], "Gate red triage")


class TestRecordsAcceptBoth(unittest.TestCase):
    """Extractors must accept pre-parsed dicts, so a tail is parsed once per tick
    instead of once per extractor. They took 5.2 passes over every line."""

    def test_as_records_parses_strings(self):
        got = ccwho.as_records([json.dumps({"type": "user"})])
        self.assertEqual(got[0]["type"], "user")

    def test_as_records_passes_dicts_through(self):
        d = {"type": "user"}
        self.assertIs(ccwho.as_records([d])[0], d)

    def test_as_records_skips_junk(self):
        self.assertEqual(ccwho.as_records(["{bad", None, 7]), [])

    def test_as_records_skips_valid_json_that_is_not_an_object(self):
        # "123" and "[1,2]" parse fine but are not records; without the dict
        # guard they reach the extractors and blow up on .get()
        self.assertEqual(ccwho.as_records(["123", "[1,2]", '"str"', "null"]), [])

    def test_title_from_dicts(self):
        self.assertEqual(ccwho.extract_title([{"type": "ai-title", "aiTitle": "T"}]), "T")

    def test_doing_from_dicts(self):
        recs = [{"type": "assistant", "message": {"content": [
            {"type": "tool_use", "name": "Bash", "input": {"description": "go"}}]}}]
        self.assertEqual(ccwho.extract_doing(recs), "Bash: go")

    def test_topic_from_dicts(self):
        recs = [{"type": "user", "message": {"content": "hello there"}}]
        self.assertEqual(ccwho.extract_topic(recs)["last"], "hello there")

    def test_last_turn_ts_from_dicts(self):
        recs = [{"type": "assistant", "timestamp": "2026-08-31T12:00:00.000Z"}]
        self.assertAlmostEqual(ccwho.last_turn_ts(recs), 1788177600.0, places=0)

    def test_waiting_kind_from_dicts(self):
        recs = [{"type": "assistant", "message": {"content": [
            {"type": "tool_use", "id": "t1", "name": "Bash", "input": {}}]}}]
        self.assertEqual(ccwho.waiting_kind(recs), "blocked")


class TestWindowCache(unittest.TestCase):
    def test_fresh_entry_is_valid(self):
        self.assertTrue(ccwho.cache_valid({"mtime": 5.0, "size": 100}, 5.0, 100))

    def test_changed_mtime_invalidates(self):
        self.assertFalse(ccwho.cache_valid({"mtime": 5.0, "size": 100}, 6.0, 100))

    def test_changed_size_invalidates(self):
        self.assertFalse(ccwho.cache_valid({"mtime": 5.0, "size": 100}, 5.0, 101))

    def test_missing_entry_invalidates(self):
        self.assertFalse(ccwho.cache_valid(None, 5.0, 100))

    def test_incomplete_entry_invalidates(self):
        self.assertFalse(ccwho.cache_valid({"mtime": 5.0}, 5.0, 100))


class TestWorkDescendants(unittest.TestCase):
    """A session that is not busy has either stopped, or is waiting on background
    work. Only the first needs you. MCP servers are infrastructure, not work."""

    PS = "\n".join([
        "  PID  PPID COMMAND",
        " 100     1 claude",
        " 101   100 npm exec chrome-devtools-mcp@latest --isolated",
        " 102   101 chrome-devtools-mcp",
        " 103   102 /Users/me/.npm/_npx/15c6/node/mcp.js",
        " 200     1 claude",
        " 201   200 /bin/zsh -c source /Users/me/.claude/shell-snapshots/x",
        " 202   201 node vitest",
    ])

    def test_session_with_only_mcp_has_no_work(self):
        self.assertEqual(ccwho.work_descendants(self.PS, 100), 0)

    def test_session_running_a_command_has_work(self):
        self.assertEqual(ccwho.work_descendants(self.PS, 200), 2)

    def test_grandchildren_count(self):
        ps = "\n".join(["  PID  PPID COMMAND", " 300     1 claude",
                        " 301   300 bash x", " 302   301 node y"])
        self.assertEqual(ccwho.work_descendants(ps, 300), 2)

    def test_unknown_pid_is_zero(self):
        self.assertEqual(ccwho.work_descendants(self.PS, 999), 0)

    def test_none_pid_is_zero(self):
        self.assertEqual(ccwho.work_descendants(self.PS, None), 0)

    def test_a_parent_cycle_terminates(self):
        ps = "\n".join(["  PID  PPID COMMAND", " 400   401 a", " 401   400 b"])
        self.assertEqual(ccwho.work_descendants(ps, 400), 1)


class TestStoppedVsRunning(unittest.TestCase):
    SESSION = {"sessionId": "s1", "cwd": "/Users/x/projects/liveapp",
               "status": "idle", "name": "n", "startedAt": 1788000000000}

    def _turn(self, text):
        return {"type": "assistant", "timestamp": "2026-08-31T12:00:00.000Z",
                "message": {"content": [{"type": "text", "text": text}]}}

    def test_not_busy_with_no_work_is_stopped(self):
        row = ccwho.build_row(self.SESSION, [], [self._turn("All done.")],
                              mtime=0, now=1788177600.0, work=0)
        self.assertEqual(row["attention"], "stopped")

    def test_not_busy_with_background_work_is_running(self):
        row = ccwho.build_row(self.SESSION, [], [self._turn("All done.")],
                              mtime=0, now=1788177600.0, work=3)
        self.assertEqual(row["attention"], "running")

    def test_an_ask_still_wins_over_stopped(self):
        row = ccwho.build_row(self.SESSION, [], [self._turn("Want me to land it?")],
                              mtime=0, now=1788177600.0, work=0)
        self.assertEqual(row["attention"], "asks")

    def test_an_ask_while_background_work_runs_still_asks(self):
        row = ccwho.build_row(self.SESSION, [], [self._turn("Want me to land it?")],
                              mtime=0, now=1788177600.0, work=5)
        self.assertEqual(row["attention"], "asks")

    def test_busy_is_untouched_by_work_count(self):
        s = dict(self.SESSION, status="busy")
        row = ccwho.build_row(s, [], [self._turn("x")], mtime=0, now=1788177600.0, work=0)
        self.assertEqual(row["attention"], "busy")

    def test_stopped_outranks_busy(self):
        rows = [{"attention": "busy", "ts": 9, "project": "a", "name": "b"},
                {"attention": "stopped", "ts": 1, "project": "a", "name": "s"}]
        self.assertEqual([r["name"] for r in sorted(rows, key=ccwho.sort_key)], ["s", "b"])

    def test_running_sorts_last(self):
        rows = [{"attention": "running", "ts": 9, "project": "a", "name": "r"},
                {"attention": "busy", "ts": 1, "project": "a", "name": "b"}]
        self.assertEqual([r["name"] for r in sorted(rows, key=ccwho.sort_key)], ["b", "r"])


class TestTtyMap(unittest.TestCase):
    PS = "\n".join([
        "  PID TTY",
        "19576 ttys032",
        "26581 ttys062",
        " 1234 ??",
    ])

    def test_maps_pid_to_tty(self):
        self.assertEqual(ccwho.parse_tty_map(self.PS)[19576], "ttys032")

    def test_no_controlling_terminal_is_omitted(self):
        self.assertNotIn(1234, ccwho.parse_tty_map(self.PS))

    def test_header_is_skipped(self):
        self.assertNotIn("PID", ccwho.parse_tty_map(self.PS))

    def test_empty_input(self):
        self.assertEqual(ccwho.parse_tty_map(""), {})


class TestShortTty(unittest.TestCase):
    def test_strips_dev_and_tty(self):
        self.assertEqual(ccwho.short_tty("/dev/ttys032"), "s032")

    def test_bare_form(self):
        self.assertEqual(ccwho.short_tty("ttys032"), "s032")

    def test_empty(self):
        self.assertEqual(ccwho.short_tty(""), "")

    def test_unknown_shape_passes_through(self):
        self.assertEqual(ccwho.short_tty("console"), "console")


class TestMatchRows(unittest.TestCase):
    ROWS = [
        {"pid": 19576, "tty": "ttys032", "title": "Liveapp temp directory leak", "project": "liveapp"},
        {"pid": 26581, "tty": "ttys062", "title": "Managing multiple Claude Code shells", "project": "liveapp"},
        {"pid": 73336, "tty": "ttys147", "title": "Vitest cleanup", "project": "liveapp"},
    ]

    def test_matches_by_pid(self):
        self.assertEqual(ccwho.match_rows(self.ROWS, "19576")[0]["pid"], 19576)

    def test_matches_by_tty_short_form(self):
        self.assertEqual(ccwho.match_rows(self.ROWS, "s062")[0]["pid"], 26581)

    def test_matches_by_title_substring_case_insensitive(self):
        self.assertEqual(ccwho.match_rows(self.ROWS, "vitest")[0]["pid"], 73336)

    def test_returns_all_matches_when_ambiguous(self):
        self.assertEqual(len(ccwho.match_rows(self.ROWS, "liveapp")), 3)

    def test_no_match_is_empty(self):
        self.assertEqual(ccwho.match_rows(self.ROWS, "zzzz"), [])

    def test_empty_query_matches_nothing(self):
        self.assertEqual(ccwho.match_rows(self.ROWS, ""), [])


class TestReadyCollapsesIntoStopped(unittest.TestCase):
    """`waiting` with nothing pending is not a separate state: it is stopped or
    running like any other non-busy session, decided by what is in flight."""

    SESSION = {"sessionId": "s1", "cwd": "/Users/x/projects/liveapp",
               "status": "waiting", "name": "n", "startedAt": 1788000000000}

    def _turn(self, text="done."):
        return {"type": "assistant", "timestamp": "2026-08-31T12:00:00.000Z",
                "message": {"content": [{"type": "text", "text": text}]}}

    def test_waiting_with_nothing_pending_and_no_work_is_stopped(self):
        row = ccwho.build_row(self.SESSION, [], [self._turn()], mtime=0,
                              now=1788177600.0, work=0)
        self.assertEqual(row["attention"], "stopped")

    def test_waiting_with_nothing_pending_but_work_is_running(self):
        row = ccwho.build_row(self.SESSION, [], [self._turn()], mtime=0,
                              now=1788177600.0, work=2)
        self.assertEqual(row["attention"], "running")

    def test_waiting_with_a_pending_tool_is_still_blocked(self):
        tail = [{"type": "assistant", "timestamp": "2026-08-31T12:00:00.000Z",
                 "message": {"content": [{"type": "tool_use", "id": "t1",
                                          "name": "Bash", "input": {}}]}}]
        row = ccwho.build_row(self.SESSION, [], tail, mtime=0, now=1788177600.0, work=0)
        self.assertEqual(row["attention"], "blocked")

    def test_ready_is_no_longer_produced(self):
        row = ccwho.build_row(self.SESSION, [], [self._turn()], mtime=0,
                              now=1788177600.0, work=0)
        self.assertNotEqual(row["attention"], "ready")


class TestOsc8(unittest.TestCase):
    """OSC 8 makes the tty column a real hyperlink. iTerm2 renders it; clicking
    hands the URL to LaunchServices, where a tiny applet turns it into a jump."""

    def test_wraps_label_in_an_osc8_sequence(self):
        got = ccwho.osc8("s032", "ccwho://jump/s032", enabled=True)
        self.assertEqual(got, "\033]8;;ccwho://jump/s032\033\\s032\033]8;;\033\\")

    def test_disabled_returns_the_bare_label(self):
        self.assertEqual(ccwho.osc8("s032", "ccwho://jump/s032", enabled=False), "s032")

    def test_empty_url_returns_the_bare_label(self):
        self.assertEqual(ccwho.osc8("s032", "", enabled=True), "s032")

    def test_label_length_is_what_gets_padded(self):
        # the escape must not count toward column width
        self.assertEqual(ccwho.visible_len(ccwho.osc8("s032", "ccwho://jump/s032", True)), 4)

    def test_visible_len_of_plain_text(self):
        self.assertEqual(ccwho.visible_len("s032"), 4)

    def test_visible_len_ignores_colour_codes(self):
        self.assertEqual(ccwho.visible_len("\033[2ms032\033[0m"), 4)


class TestJumpUrl(unittest.TestCase):
    def test_prefers_tty(self):
        self.assertEqual(ccwho.jump_url({"tty": "ttys032", "pid": 19576}),
                         "ccwho://jump/s032")

    def test_falls_back_to_pid(self):
        self.assertEqual(ccwho.jump_url({"tty": "", "pid": 19576}),
                         "ccwho://jump/19576")

    def test_empty_when_neither(self):
        self.assertEqual(ccwho.jump_url({"tty": "", "pid": None}), "")

    def test_parse_round_trip(self):
        self.assertEqual(ccwho.parse_jump_url("ccwho://jump/s032"), "s032")

    def test_parse_tolerates_trailing_slash(self):
        self.assertEqual(ccwho.parse_jump_url("ccwho://jump/s032/"), "s032")

    def test_parse_rejects_other_schemes(self):
        self.assertEqual(ccwho.parse_jump_url("http://evil/jump/s032"), "")

    def test_parse_rejects_a_scheme_crafted_to_survive_the_slice(self):
        # "https://evil/" is exactly as long as "ccwho://jump/", so without the
        # scheme check this yields a perfectly valid-looking target
        self.assertEqual(ccwho.parse_jump_url("https://evil/s032"), "")

    def test_parse_rejects_shell_metacharacters(self):
        self.assertEqual(ccwho.parse_jump_url("ccwho://jump/s032;rm -rf /"), "")

    def test_parse_empty(self):
        self.assertEqual(ccwho.parse_jump_url(""), "")
